/* UNIX 端末入出力 シミュレーター プリセット */

import type { Preset, SimOp } from "./types.js";
import { defaultConfig } from "./engine.js";

export const PRESETS: Preset[] = [
  {
    name: "正規モード（行入力）",
    description: "ICANONモードでの行バッファリングとエコー",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── 正規モード: 改行まで入力バッファに蓄積 ──" },
        { op: "tcgetattr" },
        { op: "write_stdout", text: "$ " },
        { op: "keypress", char: "h" },
        { op: "keypress", char: "e" },
        { op: "keypress", char: "l" },
        { op: "keypress", char: "l" },
        { op: "keypress", char: "o" },
        { op: "comment", text: "── バッファ: 'hello' (まだreadに渡されない) ──" },
        { op: "keypress", char: "\n" },
        { op: "comment", text: "── 改行でバッファフラッシュ → readに渡される ──" },
        { op: "read_stdin" },
        { op: "write_stdout", text: "hello, world!\n" },
      ],
    }],
  },
  {
    name: "rawモード（即時入力）",
    description: "rawモードでの1文字ずつ即時読み取り",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── rawモードに切替: エコーなし、バッファなし ──" },
        { op: "set_raw" },
        { op: "tcgetattr" },
        { op: "keypress", char: "a" },
        { op: "read_stdin" },
        { op: "comment", text: "── 1文字ずつ即座にreadに渡される ──" },
        { op: "keypress", char: "b" },
        { op: "read_stdin" },
        { op: "keypress", char: "\x03" },
        { op: "comment", text: "── Ctrl+C もシグナルにならず文字データとして読める ──" },
        { op: "read_stdin" },
        { op: "comment", text: "── 正規モード復元 ──" },
        { op: "set_canonical" },
        { op: "tcgetattr" },
      ],
    }],
  },
  {
    name: "cbreakモード",
    description: "シグナル有効、エコーなし、バッファなし",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── cbreakモード: ISIG=on, ICANON=off, ECHO=off ──" },
        { op: "set_cbreak" },
        { op: "tcgetattr" },
        { op: "keypress", char: "x" },
        { op: "read_stdin" },
        { op: "comment", text: "── 即座に読み取れるがエコーなし ──" },
        { op: "keypress", char: "\x03" },
        { op: "comment", text: "── Ctrl+C はシグナルとして処理 (ISIG=on) ──" },
        { op: "set_canonical" },
      ],
    }],
  },
  {
    name: "シグナル生成（Ctrl+C/Z）",
    description: "制御文字によるシグナル配送とプロセス制御",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── フォアグラウンドプロセスにシグナル配送 ──" },
        { op: "spawn", name: "vim", pgid: 2 },
        { op: "fg_process", pid: 2 },
        { op: "write_stdout", text: "vim: editing file...\n" },
        { op: "comment", text: "── Ctrl+Z: SIGTSTP → プロセス停止 ──" },
        { op: "keypress", char: "\x1a" },
        { op: "comment", text: "── shellがフォアグラウンドに復帰 ──" },
        { op: "fg_process", pid: 1 },
        { op: "write_stdout", text: "[1]+ Stopped  vim\n$ " },
        { op: "comment", text: "── fg でvimを再開 ──" },
        { op: "fg_process", pid: 2 },
        { op: "write_stdout", text: "vim: resumed\n" },
        { op: "comment", text: "── Ctrl+C: SIGINT → プロセス終了 ──" },
        { op: "keypress", char: "\x03" },
        { op: "fg_process", pid: 1 },
        { op: "write_stdout", text: "$ " },
      ],
    }],
  },
  {
    name: "行編集（Backspace/Ctrl+U）",
    description: "正規モードの行編集機能",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "write_stdout", text: "$ " },
        { op: "keypress", char: "c" },
        { op: "keypress", char: "a" },
        { op: "keypress", char: "t" },
        { op: "comment", text: "── 'cat' を入力中。Backspaceで修正 ──" },
        { op: "keypress", char: "\x7f" },
        { op: "comment", text: "── 't' が削除された (VERASE) ──" },
        { op: "keypress", char: "\x7f" },
        { op: "comment", text: "── 'a' が削除された ──" },
        { op: "keypress", char: "p" },
        { op: "comment", text: "── 'cp' になった ──" },
        { op: "keypress", char: "\x15" },
        { op: "comment", text: "── Ctrl+U: 行全体を削除 (VKILL) ──" },
        { op: "keypress", char: "l" },
        { op: "keypress", char: "s" },
        { op: "keypress", char: "\n" },
        { op: "read_stdin" },
      ],
    }],
  },
  {
    name: "EOF (Ctrl+D)",
    description: "Ctrl+Dによるファイル終端の処理",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── バッファに文字がある状態でCtrl+D ──" },
        { op: "write_stdout", text: "> " },
        { op: "keypress", char: "A" },
        { op: "keypress", char: "B" },
        { op: "keypress", char: "C" },
        { op: "keypress", char: "\x04" },
        { op: "comment", text: "── Ctrl+D: バッファ 'ABC' を改行なしでフラッシュ ──" },
        { op: "read_stdin" },
        { op: "comment", text: "── 空バッファでCtrl+D → EOF (read returns 0) ──" },
        { op: "write_stdout", text: "> " },
        { op: "keypress", char: "\x04" },
        { op: "read_stdin" },
        { op: "comment", text: "── read = 0: ファイル終端検出 ──" },
      ],
    }],
  },
  {
    name: "CR/NL変換",
    description: "入力のICRNLと出力のONLCR変換",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── ICRNL=on: Enter(CR) → NL に変換 ──" },
        { op: "tcgetattr" },
        { op: "keypress", char: "H" },
        { op: "keypress", char: "i" },
        { op: "keypress", char: "\r" },
        { op: "comment", text: "── CR が NL に変換されて行完成 ──" },
        { op: "read_stdin" },
        { op: "comment", text: "── ONLCR=on: 出力の NL → CR+NL ──" },
        { op: "write_stdout", text: "Line1\nLine2\nLine3\n" },
        { op: "comment", text: "── ICRNL=off にして CR をそのまま渡す ──" },
        { op: "tcsetattr", changes: { iflag: { ICRNL: false } } },
        { op: "keypress", char: "\r" },
        { op: "comment", text: "── CR のまま（NLに変換されない） ──" },
      ],
    }],
  },
  {
    name: "フロー制御（Ctrl+S/Q）",
    description: "XON/XOFF による出力の停止と再開",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── IXON フロー制御の動作 ──" },
        { op: "write_stdout", text: "output line 1\n" },
        { op: "write_stdout", text: "output line 2\n" },
        { op: "keypress", char: "\x13" },
        { op: "comment", text: "── Ctrl+S (XOFF): 出力停止 ──" },
        { op: "write_stdout", text: "output line 3\n" },
        { op: "write_stdout", text: "output line 4\n" },
        { op: "comment", text: "── 出力はバッファリングされている ──" },
        { op: "keypress", char: "\x11" },
        { op: "comment", text: "── Ctrl+Q (XON): 出力再開 ──" },
        { op: "write_stdout", text: "output line 5\n" },
      ],
    }],
  },
  {
    name: "擬似端末 (PTY)",
    description: "pty master/slave の動作",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── PTYの作成と使用 ──" },
        { op: "pty_open" },
        { op: "comment", text: "── マスター側からスレーブへ書き込み ──" },
        { op: "pty_write", text: "Hello from master\n" },
        { op: "comment", text: "── スレーブ側の入力をマスターから読み取り ──" },
        { op: "keypress", char: "c" },
        { op: "keypress", char: "m" },
        { op: "keypress", char: "d" },
        { op: "keypress", char: "\n" },
        { op: "pty_read" },
        { op: "comment", text: "── PTYはssh/tmux/screenの基盤技術 ──" },
        { op: "pty_write", text: "$ command output\n" },
      ],
    }],
  },
  {
    name: "ANSIエスケープシーケンス",
    description: "端末制御のエスケープシーケンス",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(), ttyName: "/dev/tty1",
      instructions: [
        { op: "comment", text: "── ANSIエスケープシーケンスによる端末制御 ──" },
        { op: "write_stdout", text: "Normal text\n" },
        { op: "ansi_escape", seq: "[31m", desc: "文字色: 赤" },
        { op: "write_stdout", text: "Red text" },
        { op: "ansi_escape", seq: "[0m", desc: "リセット" },
        { op: "write_stdout", text: "\n" },
        { op: "ansi_escape", seq: "[1m", desc: "太字" },
        { op: "write_stdout", text: "Bold text" },
        { op: "ansi_escape", seq: "[0m", desc: "リセット" },
        { op: "write_stdout", text: "\n" },
        { op: "ansi_escape", seq: "[2J", desc: "画面クリア" },
        { op: "ansi_escape", seq: "[H", desc: "カーソルをホーム位置へ" },
        { op: "write_stdout", text: "After clear\n" },
        { op: "ansi_escape", seq: "[5;10H", desc: "カーソルを5行10列へ移動" },
        { op: "write_stdout", text: "Positioned text" },
      ],
    }],
  },
];
