/* ネットワークプリンタ シミュレーター プリセット */

import type { Preset, SimOp } from "./types.js";
import { defaultConfig } from "./engine.js";

/** 共通プリンタ定義 */
const laserBW = {
  id: "lj-01", name: "LaserJet-01", type: "laser_bw" as const,
  ip: "192.168.1.100", mac: "00:1A:2B:3C:4D:01",
  state: "idle" as const, ppm: 30,
  paperRemaining: 250, tonerLevel: 80,
  protocols: ["ipp" as const, "lpd" as const, "raw9100" as const, "snmp" as const, "bonjour" as const],
  duplex: true, color: false, warmupTicks: 3,
};

const laserColor = {
  id: "cl-01", name: "ColorLaser-01", type: "laser_color" as const,
  ip: "192.168.1.101", mac: "00:1A:2B:3C:4D:02",
  state: "idle" as const, ppm: 20,
  paperRemaining: 500, tonerLevel: 60,
  protocols: ["ipp" as const, "raw9100" as const, "snmp" as const, "ws_discovery" as const],
  duplex: true, color: true, warmupTicks: 4,
};

const inkjet = {
  id: "ij-01", name: "InkJet-01", type: "inkjet" as const,
  ip: "192.168.1.102", mac: "00:1A:2B:3C:4D:03",
  state: "idle" as const, ppm: 12,
  paperRemaining: 100, tonerLevel: 45,
  protocols: ["ipp" as const, "bonjour" as const],
  duplex: false, color: true, warmupTicks: 1,
};

const clientPC = { name: "PC-A", ip: "192.168.1.10", os: "Windows 11" };
const clientMac = { name: "Mac-B", ip: "192.168.1.11", os: "macOS" };

export const PRESETS: Preset[] = [
  {
    name: "基本的な印刷フロー",
    description: "IPPプロトコルで文書を送信し、転送→処理→印刷の一連の流れ",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── ネットワークプリンタ: 基本印刷フロー ──" },
        { op: "add_printer", printer: laserBW },
        { op: "add_client", client: clientPC },
        { op: "comment", text: "── IPP (TCP/631) でジョブ送信 ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "四半期報告書.pdf", owner: "田中", sourceIp: "192.168.1.10",
          pages: 10, paperSize: "A4", quality: "normal", color: false,
          duplex: true, copies: 1, sizeBytes: 524288, protocol: "ipp", priority: 5,
        }},
        { op: "comment", text: "── データ転送 (IPP: 64KB/tick) ──" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "comment", text: "── キューからジョブを取り出して処理 ──" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "comment", text: "── ウォームアップ (レーザー定着器の加熱) ──" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "comment", text: "── 印刷開始 ──" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "comment", text: "── ページ出力完了 ──" },
      ],
    }],
  },
  {
    name: "プロトコル探索 (Bonjour/WS-Discovery)",
    description: "ネットワーク上のプリンタをmDNSとWS-Discoveryで自動探索",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── プリンタの自動探索 ──" },
        { op: "add_printer", printer: laserBW },
        { op: "add_printer", printer: laserColor },
        { op: "add_printer", printer: inkjet },
        { op: "add_client", client: clientPC },
        { op: "add_client", client: clientMac },
        { op: "comment", text: "── Mac: Bonjour (mDNS) で探索 ──" },
        { op: "discover", clientName: "Mac-B", protocol: "bonjour" },
        { op: "comment", text: "── PC: WS-Discovery で探索 ──" },
        { op: "discover", clientName: "PC-A", protocol: "ws_discovery" },
        { op: "comment", text: "── PC: IPP でも探索 ──" },
        { op: "discover", clientName: "PC-A", protocol: "ipp" },
        { op: "comment", text: "── SNMP でステータス確認 ──" },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "snmp" },
        { op: "status_query", clientName: "PC-A", printerName: "ColorLaser-01", protocol: "snmp" },
        { op: "comment", text: "── 各プロトコルでの探索結果が異なる ──" },
      ],
    }],
  },
  {
    name: "複数ジョブのキュー管理",
    description: "優先度付きキュー: 複数クライアントからの同時印刷要求",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── 複数ジョブの優先度管理 ──" },
        { op: "add_printer", printer: laserBW },
        { op: "add_client", client: clientPC },
        { op: "add_client", client: clientMac },
        { op: "comment", text: "── 通常優先度のジョブ ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "会議資料.pdf", owner: "佐藤", sourceIp: "192.168.1.10",
          pages: 20, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 3, sizeBytes: 1048576, protocol: "ipp", priority: 5,
        }},
        { op: "submit_job", clientName: "Mac-B", printerName: "LaserJet-01", job: {
          name: "契約書.pdf", owner: "鈴木", sourceIp: "192.168.1.11",
          pages: 5, paperSize: "A4", quality: "high", color: false,
          duplex: true, copies: 1, sizeBytes: 262144, protocol: "ipp", priority: 7,
        }},
        { op: "comment", text: "── 高優先度の緊急ジョブ ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "【至急】役員報告.pdf", owner: "山田部長", sourceIp: "192.168.1.10",
          pages: 3, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 1, sizeBytes: 131072, protocol: "raw9100", priority: 1,
        }},
        { op: "comment", text: "── データ転送 ──" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "comment", text: "── 優先度1の至急ジョブが先に処理される ──" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
      ],
    }],
  },
  {
    name: "紙詰まりとエラー復旧",
    description: "印刷中の紙詰まり発生 → ジャムクリア → 印刷再開",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── 紙詰まり発生シナリオ ──" },
        { op: "add_printer", printer: laserBW },
        { op: "add_client", client: clientPC },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "大量印刷.pdf", owner: "田中", sourceIp: "192.168.1.10",
          pages: 30, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 1, sizeBytes: 131072, protocol: "raw9100", priority: 5,
        }},
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "comment", text: "── 印刷中... ──" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "comment", text: "── !! 紙詰まり発生 !! ──" },
        { op: "paper_jam", printerName: "LaserJet-01" },
        { op: "comment", text: "── 印刷停止、エラー状態 ──" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "snmp" },
        { op: "comment", text: "── ユーザーがジャムクリア ──" },
        { op: "clear_jam", printerName: "LaserJet-01" },
        { op: "comment", text: "── 印刷再開 ──" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
      ],
    }],
  },
  {
    name: "用紙切れと補充",
    description: "印刷中に用紙切れ → 用紙補充 → 印刷再開",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── 用紙切れシナリオ ──" },
        { op: "add_printer", printer: {
          ...laserBW, paperRemaining: 8,
        }},
        { op: "add_client", client: clientPC },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "レポート.pdf", owner: "高橋", sourceIp: "192.168.1.10",
          pages: 15, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 1, sizeBytes: 65536, protocol: "ipp", priority: 5,
        }},
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "comment", text: "── 用紙残量: わずか ──" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "comment", text: "── 用紙切れ! ──" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "ipp" },
        { op: "comment", text: "── 用紙補充 (500枚) ──" },
        { op: "add_paper", printerName: "LaserJet-01", sheets: 500 },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "comment", text: "── 残りページ印刷完了 ──" },
      ],
    }],
  },
  {
    name: "カラーレーザー印刷",
    description: "カラーレーザーでの大判カラー印刷とトナー消費",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── カラーレーザー印刷 ──" },
        { op: "add_printer", printer: { ...laserColor, tonerLevel: 15 } },
        { op: "add_client", client: clientMac },
        { op: "comment", text: "── カラー写真入り企画書を印刷 ──" },
        { op: "submit_job", clientName: "Mac-B", printerName: "ColorLaser-01", job: {
          name: "企画書_カラー.pdf", owner: "伊藤", sourceIp: "192.168.1.11",
          pages: 20, paperSize: "A4", quality: "high", color: true,
          duplex: true, copies: 2, sizeBytes: 2097152, protocol: "ipp", priority: 3,
        }},
        { op: "comment", text: "── 大容量データ転送 ──" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "process_queue", printerName: "ColorLaser-01" },
        { op: "comment", text: "── カラーレーザーのウォームアップ (4 tick) ──" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "process_queue", printerName: "ColorLaser-01" },
        { op: "comment", text: "── カラー印刷: トナー消費が倍 (0.3%/p) ──" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "print_tick", printerName: "ColorLaser-01" },
        { op: "comment", text: "── トナー残量に注目 ──" },
        { op: "status_query", clientName: "Mac-B", printerName: "ColorLaser-01", protocol: "ipp" },
      ],
    }],
  },
  {
    name: "プロトコル比較 (IPP vs LPD vs Raw)",
    description: "同じジョブを異なるプロトコルで送信し転送速度を比較",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── プロトコル別転送速度の比較 ──" },
        { op: "add_printer", printer: laserBW },
        { op: "add_client", client: clientPC },
        { op: "comment", text: "── 1. LPD (TCP/515): 32KB/tick ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "test_lpd.pdf", owner: "テスト", sourceIp: "192.168.1.10",
          pages: 5, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 1, sizeBytes: 131072, protocol: "lpd", priority: 5,
        }},
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "comment", text: "── 2. IPP (TCP/631): 64KB/tick ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "test_ipp.pdf", owner: "テスト", sourceIp: "192.168.1.10",
          pages: 5, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 1, sizeBytes: 131072, protocol: "ipp", priority: 5,
        }},
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "comment", text: "── 3. Raw 9100 (TCP/9100): 128KB/tick ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "test_raw.pdf", owner: "テスト", sourceIp: "192.168.1.10",
          pages: 5, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 1, sizeBytes: 131072, protocol: "raw9100", priority: 5,
        }},
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "comment", text: "── Raw9100が1tickで転送完了 (128KB > 128KB) ──" },
        { op: "comment", text: "── LPD: 4tick / IPP: 2tick / Raw: 1tick ──" },
      ],
    }],
  },
  {
    name: "ジョブキャンセルとオフライン",
    description: "印刷ジョブのキャンセル操作とプリンタのオフライン設定",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── ジョブキャンセルとオフライン操作 ──" },
        { op: "add_printer", printer: laserBW },
        { op: "add_client", client: clientPC },
        { op: "add_client", client: clientMac },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "不要な資料.pdf", owner: "佐藤", sourceIp: "192.168.1.10",
          pages: 50, paperSize: "A4", quality: "draft", color: false,
          duplex: false, copies: 1, sizeBytes: 65536, protocol: "ipp", priority: 5,
        }},
        { op: "submit_job", clientName: "Mac-B", printerName: "LaserJet-01", job: {
          name: "重要文書.pdf", owner: "鈴木", sourceIp: "192.168.1.11",
          pages: 10, paperSize: "A4", quality: "high", color: false,
          duplex: true, copies: 1, sizeBytes: 65536, protocol: "ipp", priority: 3,
        }},
        { op: "comment", text: "── Job#1をキャンセル ──" },
        { op: "cancel_job", printerName: "LaserJet-01", jobId: 1 },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "ipp" },
        { op: "comment", text: "── プリンタをオフラインに設定 ──" },
        { op: "set_offline", printerName: "LaserJet-01" },
        { op: "comment", text: "── オフライン中はジョブ送信失敗 ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "送れない.pdf", owner: "田中", sourceIp: "192.168.1.10",
          pages: 1, paperSize: "A4", quality: "draft", color: false,
          duplex: false, copies: 1, sizeBytes: 1024, protocol: "ipp", priority: 5,
        }},
        { op: "comment", text: "── オンラインに復帰 ──" },
        { op: "set_online", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "comment", text: "── 残りのJob#2が処理される ──" },
      ],
    }],
  },
  {
    name: "複数プリンタの負荷分散",
    description: "3台のプリンタに対して複数ジョブを分散配置",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── 複数プリンタの負荷分散 ──" },
        { op: "add_printer", printer: laserBW },
        { op: "add_printer", printer: laserColor },
        { op: "add_printer", printer: inkjet },
        { op: "add_client", client: clientPC },
        { op: "add_client", client: clientMac },
        { op: "comment", text: "── モノクロ文書 → LaserJet ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "議事録.txt", owner: "佐藤", sourceIp: "192.168.1.10",
          pages: 8, paperSize: "A4", quality: "draft", color: false,
          duplex: true, copies: 5, sizeBytes: 32768, protocol: "raw9100", priority: 5,
        }},
        { op: "comment", text: "── カラープレゼン → ColorLaser ──" },
        { op: "submit_job", clientName: "Mac-B", printerName: "ColorLaser-01", job: {
          name: "プレゼン.pptx", owner: "伊藤", sourceIp: "192.168.1.11",
          pages: 15, paperSize: "A4", quality: "high", color: true,
          duplex: false, copies: 1, sizeBytes: 1048576, protocol: "ipp", priority: 3,
        }},
        { op: "comment", text: "── 写真印刷 → InkJet ──" },
        { op: "submit_job", clientName: "Mac-B", printerName: "InkJet-01", job: {
          name: "写真.jpg", owner: "伊藤", sourceIp: "192.168.1.11",
          pages: 4, paperSize: "A4", quality: "high", color: true,
          duplex: false, copies: 1, sizeBytes: 524288, protocol: "ipp", priority: 5,
        }},
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "InkJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "InkJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "InkJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "InkJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "InkJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "InkJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "InkJet-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "transfer_data", printerName: "ColorLaser-01" },
        { op: "comment", text: "── 3台同時に処理開始 ──" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "ColorLaser-01" },
        { op: "process_queue", printerName: "InkJet-01" },
        { op: "comment", text: "── 各プリンタの速度差に注目 ──" },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "snmp" },
        { op: "status_query", clientName: "PC-A", printerName: "ColorLaser-01", protocol: "snmp" },
        { op: "status_query", clientName: "Mac-B", printerName: "InkJet-01", protocol: "ipp" },
      ],
    }],
  },
  {
    name: "トナー交換",
    description: "トナー残量低下→交換→印刷再開の流れ",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── トナー残量管理 ──" },
        { op: "add_printer", printer: { ...laserBW, tonerLevel: 5 } },
        { op: "add_client", client: clientPC },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "snmp" },
        { op: "comment", text: "── トナー残量5%で印刷開始 ──" },
        { op: "submit_job", clientName: "PC-A", printerName: "LaserJet-01", job: {
          name: "長文レポート.pdf", owner: "中村", sourceIp: "192.168.1.10",
          pages: 50, paperSize: "A4", quality: "normal", color: false,
          duplex: false, copies: 1, sizeBytes: 65536, protocol: "raw9100", priority: 5,
        }},
        { op: "transfer_data", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "comment", text: "── トナー切れで停止 ──" },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "snmp" },
        { op: "comment", text: "── 新しいトナーカートリッジに交換 ──" },
        { op: "replace_toner", printerName: "LaserJet-01" },
        { op: "comment", text: "── 印刷再開 ──" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "process_queue", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "print_tick", printerName: "LaserJet-01" },
        { op: "status_query", clientName: "PC-A", printerName: "LaserJet-01", protocol: "snmp" },
      ],
    }],
  },
];
