/*
 * Unix V6 シミュレーター プリセット
 *
 * V6の主要サブシステムを学習するための41個のプリセットシナリオ。
 * 各プリセットはV6Operation列を構築し、特定のカーネル機能を段階的にデモする。
 *
 * Lions本の章構成(9章)との対応を【】で示す。
 *
 * ─── プロセスサブシステム 【第1章: プロセス】 ───
 *  1. ブートシーケンス — カーネル起動からinit/getty
 *  2. fork/exec/waitライフサイクル — プロセスモデルの核心
 * 11. ゾンビ蓄積 — 親がwaitしないとゾンビが溜まる問題
 * 12. 孤児プロセスのinit再配置 — 親が先に終了するケース
 * 16. プロセス優先度とnice — スケジューラの挙動観察
 * 17. デーモンプロセス — ダブルforkパターン
 * 23. バックグラウンド実行 (&) — waitしないforkパターン
 * 34. brk()/データ領域拡張 — sbreak()によるヒープ拡張
 *
 * ─── スワッピング 【第2章: スワッピング】 ───
 * 26. スワッピングサブシステム — swap_out/in、テキストセグメント共有
 *
 * ─── 割り込みとトラップ 【第3章: 割り込み/トラップ】 ───
 * 28. 割り込みとトラップ機構 — PDP-11ベクタ、trap→sysent[]ディスパッチ
 * 32. sysent[]とシステムコールの内部構造 — syscall一覧と内部処理
 * 40. clock_tick()とcalloutテーブル — クロック割り込み処理
 *
 * ─── シグナル 【第4章: シグナル】 ───
 *  8. シグナル処理 — catch/ignore/default/SIGKILL
 * 33. 端末割り込みとシグナル配送 — psignal/issig/psigサイクル
 * 37. ptrace()デバッグ — プロセストレースの仕組み
 *
 * ─── ブロックI/Oサブシステム 【第5章: ブロックI/O】 ───
 *  7. バッファキャッシュ — ヒット/ミス/LRUエビクト/sync
 * 29. ブロックデバイスドライバ (RK11) — strategy/start/interrupt
 * 39. breada()先読みとphysio() RAW I/O — bio.c拡張機能
 *
 * ─── ファイルシステム 【第6章: ファイルシステム】 ───
 *  3. ファイル操作 — creat/write/read/unlink
 *  4. i-nodeとブロック割当 — 直接→間接ブロック遷移
 *  5. パス解決とディレクトリ — namei()コンポーネント解決
 * 13. fork後のfd共有 — 3層テーブルとオフセット共有
 * 14. オープン中のファイル削除 — unlink後のinode遅延解放
 * 15. I/Oリダイレクション (dup) — シェルの2>&1の基盤
 * 18. ハードリンクとinode共有 — nlink管理
 * 19. cat コマンド — open/read/write/closeの最小パターン
 * 20. cp コマンド — read/writeループ
 * 21. mv コマンド — link + unlink
 * 24. 同時書き込み競合 — 独立openのoffset問題
 * 25. chmod と権限管理 — パーミッションビット
 * 30. パーミッションとSUID — uid/gid/mode/setuid
 * 31. マウントとファイルシステム構造 — mount/umount/スーパーブロック
 * 35. seek()とファイルポインタ — whence 3モード
 * 36. mknod()とデバイスファイル — IFCHR/IFBLK/addr[0]
 *
 * ─── パイプ 【第7章: パイプ】 ───
 *  6. パイプ通信 — pipe/fork/read/write
 * 10. シェルパイプライン — ls|grep|wc の3段パイプ
 *
 * ─── キャラクタI/O 【第8章: キャラクタI/O】 ───
 * 27. TTY端末入出力 — clist/rawq/canq/outq/canon/特殊文字
 * 38. grow()スタック自動拡張 — MMUトラップ起因
 *
 * ─── システムブート 【第9章: ブート】 ───
 * 34. ブートシーケンス詳細 — start→main→binit→iinit→newproc→init→getty
 *  9. マルチユーザーログイン — getty→login→shell
 * 22. シェルスクリプト実行 — fork/exec/waitの連鎖
 */

import type { V6Preset } from "./types.js";
import { defaultConfig } from "./engine.js";

export const PRESETS: V6Preset[] = [
  {
    name: "ブートシーケンス",
    description: "superblock読込→root inode→ディレクトリ構造→init起動→/etc/rc実行",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "comment", text: "── Unix V6 ブートシーケンス ──" },
        { op: "boot" },
        { op: "comment", text: "── init (PID 1) が /etc/rc を実行 ──" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: ["-c", "/etc/rc"] },
        { op: "comment", text: "── rcスクリプトがシステム初期化 ──" },
        { op: "open", pid: 2, path: "/etc/rc", mode: "read" },
        { op: "read", pid: 2, fd: 0, size: 256 },
        { op: "close", pid: 2, fd: 0 },
        { op: "exit", pid: 2, code: 0 },
        { op: "wait", pid: 1 },
        { op: "comment", text: "── init がログイン用シェルを起動 ──" },
        { op: "fork", parentPid: 1, childName: "getty" },
        { op: "exec", pid: 3, path: "/etc/init", argv: ["getty"] },
        { op: "schedule" },
      ],
    }),
  },
  {
    name: "fork/exec/waitライフサイクル",
    description: "シェルがforkでコマンドを実行し、waitで回収する一連の流れ",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "comment", text: "── シェル (PID 2) が /bin/ls を実行 ──" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── sh がforkして子プロセスを作成 ──" },
        { op: "fork", parentPid: 2, childName: "ls" },
        { op: "comment", text: "── 子プロセスがexecで/bin/lsに置換 ──" },
        { op: "exec", pid: 3, path: "/bin/ls", argv: ["-l"] },
        { op: "schedule" },
        { op: "comment", text: "── ls がファイルを読んで出力 ──" },
        { op: "open", pid: 3, path: "/", mode: "read" },
        { op: "read", pid: 3, fd: 0, size: 512 },
        { op: "close", pid: 3, fd: 0 },
        { op: "comment", text: "── ls 終了 → zombie ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "comment", text: "── sh が wait で zombie を回収 ──" },
        { op: "wait", pid: 2 },
        { op: "schedule" },
      ],
    }),
  },
  {
    name: "ファイル操作 (creat/read/write/unlink)",
    description: "ファイルの作成→書き込み→クローズ→再オープン→読み込み→削除",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── creat: 新しいファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/tmp/hello.txt", perm: 0o644 },
        { op: "comment", text: "── write: データを書き込み ──" },
        { op: "write", pid: 2, fd: 0, data: "Hello, Unix V6!\n" },
        { op: "write", pid: 2, fd: 0, data: "This is a test file.\n" },
        { op: "comment", text: "── close: ファイルを閉じる ──" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── open: 再度読み込みモードで開く ──" },
        { op: "open", pid: 2, path: "/tmp/hello.txt", mode: "read" },
        { op: "comment", text: "── read: データを読み込み ──" },
        { op: "read", pid: 2, fd: 0, size: 128 },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── stat: ファイル情報を確認 ──" },
        { op: "stat", pid: 2, path: "/tmp/hello.txt" },
        { op: "comment", text: "── unlink: ファイルを削除 ──" },
        { op: "unlink", pid: 2, path: "/tmp/hello.txt" },
        { op: "comment", text: "── inode とブロックが解放される ──" },
      ],
    }),
  },
  {
    name: "i-nodeとブロック割当",
    description: "10直接ブロックを超えるファイルで間接ブロックが割り当てられる過程",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "writer" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 大きなファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/tmp/bigfile", perm: 0o644 },
        { op: "comment", text: "── 直接ブロック (addr[0]~addr[9]) に書き込み ──" },
        { op: "write", pid: 2, fd: 0, data: "block0: " + "A".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block1: " + "B".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block2: " + "C".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block3: " + "D".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block4: " + "E".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block5: " + "F".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block6: " + "G".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block7: " + "H".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block8: " + "I".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block9: " + "J".repeat(500) },
        { op: "comment", text: "── 10ブロック超過 → 間接ブロック (addr[10]) 割当 ──" },
        { op: "write", pid: 2, fd: 0, data: "block10: " + "K".repeat(500) },
        { op: "write", pid: 2, fd: 0, data: "block11: " + "L".repeat(500) },
        { op: "comment", text: "── stat でファイルサイズとinode構造を確認 ──" },
        { op: "close", pid: 2, fd: 0 },
        { op: "stat", pid: 2, path: "/tmp/bigfile" },
      ],
    }),
  },
  {
    name: "パス解決とディレクトリ",
    description: "mkdirとcreatでディレクトリ構造を作り、パス解決の過程を観察",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── ディレクトリ構造を作成 ──" },
        { op: "mkdir", pid: 2, path: "/usr/src" },
        { op: "mkdir", pid: 2, path: "/usr/src/sys" },
        { op: "comment", text: "── 深いパスにファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/usr/src/sys/main.c", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "#include <param.h>\nmain() { ... }" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── パス解決: / → usr → src → sys → main.c ──" },
        { op: "stat", pid: 2, path: "/usr/src/sys/main.c" },
        { op: "comment", text: "── chdir でカレントディレクトリ変更 ──" },
        { op: "chdir", pid: 2, path: "/usr/src/sys" },
        { op: "comment", text: "── link: ハードリンクを作成 ──" },
        { op: "link", pid: 2, existingPath: "/usr/src/sys/main.c", newPath: "/tmp/main.c" },
        { op: "stat", pid: 2, path: "/usr/src/sys/main.c" },
        { op: "comment", text: "── nlink=2: 2つのディレクトリエントリが同じinodeを指す ──" },
      ],
    }),
  },
  {
    name: "パイプ通信",
    description: "pipe()でプロセス間通信: 親が書き込み、子が読み取り",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── pipe() でパイプ作成 ──" },
        { op: "pipe", pid: 2 },
        { op: "comment", text: "── fork: 子プロセスがパイプを継承 ──" },
        { op: "fork", parentPid: 2, childName: "reader" },
        { op: "comment", text: "── 親プロセスがパイプに書き込み ──" },
        { op: "write", pid: 2, fd: 1, data: "Hello from parent!\n" },
        { op: "write", pid: 2, fd: 1, data: "Unix V6 pipe test\n" },
        { op: "comment", text: "── 子プロセスがパイプから読み取り ──" },
        { op: "read", pid: 3, fd: 0, size: 128 },
        { op: "read", pid: 3, fd: 0, size: 128 },
        { op: "comment", text: "── 親が書き込み側をクローズ ──" },
        { op: "close", pid: 2, fd: 1 },
        { op: "comment", text: "── 子プロセス終了 ──" },
        { op: "close", pid: 3, fd: 0 },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
      ],
    }),
  },
  {
    name: "バッファキャッシュ",
    description: "同じブロックの再読込でヒット、キャッシュ満杯でLRUエビクト",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── ファイルを作成して複数ブロックに書き込み ──" },
        { op: "creat", pid: 2, path: "/tmp/cache_test", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "data-block-A " + "x".repeat(400) },
        { op: "write", pid: 2, fd: 0, data: "data-block-B " + "y".repeat(400) },
        { op: "write", pid: 2, fd: 0, data: "data-block-C " + "z".repeat(400) },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── 同じファイルを再度読み込み → バッファヒット ──" },
        { op: "open", pid: 2, path: "/tmp/cache_test", mode: "read" },
        { op: "read", pid: 2, fd: 0, size: 512 },
        { op: "read", pid: 2, fd: 0, size: 512 },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── 多数のファイルを開いてキャッシュを圧迫 ──" },
        { op: "creat", pid: 2, path: "/tmp/fill1", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "fill-1" },
        { op: "close", pid: 2, fd: 0 },
        { op: "creat", pid: 2, path: "/tmp/fill2", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "fill-2" },
        { op: "close", pid: 2, fd: 0 },
        { op: "creat", pid: 2, path: "/tmp/fill3", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "fill-3" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── sync: ダーティバッファをディスクに書き戻し ──" },
        { op: "sync" },
      ],
    }),
  },
  {
    name: "シグナル処理",
    description: "SIGINT(catch)→SIGHUP(default終了)→SIGKILL(捕捉不可)",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "fork", parentPid: 2, childName: "daemon" },
        { op: "exec", pid: 3, path: "/bin/sh", argv: ["daemon"] },
        { op: "comment", text: "── シグナルハンドラを設定 ──" },
        { op: "signal", pid: 3, sig: "SIGINT", action: "catch" },
        { op: "signal", pid: 3, sig: "SIGHUP", action: "ignore" },
        { op: "comment", text: "── SIGINT送信 → ハンドラで捕捉 ──" },
        { op: "kill", senderPid: 2, targetPid: 3, sig: "SIGINT" },
        { op: "comment", text: "── SIGHUP送信 → 無視設定なので何も起きない ──" },
        { op: "kill", senderPid: 2, targetPid: 3, sig: "SIGHUP" },
        { op: "comment", text: "── SIGQUIT送信 → デフォルト動作(終了) ──" },
        { op: "kill", senderPid: 2, targetPid: 3, sig: "SIGQUIT" },
        { op: "comment", text: "── 新しいプロセスでSIGKILLテスト ──" },
        { op: "fork", parentPid: 2, childName: "victim" },
        { op: "signal", pid: 4, sig: "SIGINT", action: "ignore" },
        { op: "comment", text: "── SIGKILL は捕捉・無視不可 → 強制終了 ──" },
        { op: "kill", senderPid: 2, targetPid: 4, sig: "SIGKILL" },
        { op: "wait", pid: 2 },
        { op: "schedule" },
      ],
    }),
  },
  {
    name: "マルチユーザーログイン",
    description: "initがgettyを起動→login認証→シェル起動 × 2端末",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "comment", text: "── init が tty0 用の getty を起動 ──" },
        { op: "fork", parentPid: 1, childName: "getty" },
        { op: "exec", pid: 2, path: "/etc/init", argv: ["getty", "/dev/tty0"] },
        { op: "comment", text: "── getty → login に exec ──" },
        { op: "exec", pid: 2, path: "/etc/init", argv: ["login"] },
        { op: "comment", text: "── login 認証成功 → sh に exec ──" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── ユーザー1のシェルが起動 ──" },
        { op: "schedule" },
        { op: "comment", text: "── init が tty1 用の getty を起動 ──" },
        { op: "fork", parentPid: 1, childName: "getty" },
        { op: "exec", pid: 3, path: "/etc/init", argv: ["getty", "/dev/tty1"] },
        { op: "exec", pid: 3, path: "/etc/init", argv: ["login"] },
        { op: "exec", pid: 3, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 2つのシェルが同時に動作 ──" },
        { op: "schedule" },
        { op: "comment", text: "── ユーザー1がファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/tmp/user1.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "user1 data" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── ユーザー2が同じファイルを読む ──" },
        { op: "open", pid: 3, path: "/tmp/user1.txt", mode: "read" },
        { op: "read", pid: 3, fd: 0, size: 64 },
        { op: "close", pid: 3, fd: 0 },
        { op: "schedule" },
      ],
    }),
  },
  {
    name: "シェルパイプライン (ls | grep | wc)",
    description: "3段パイプライン: pipe×2→fork×3→dup→exec→データ流通",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── sh: ls | grep | wc パイプライン構築 ──" },
        { op: "comment", text: "── パイプ1: ls → grep ──" },
        { op: "pipe", pid: 2 },
        { op: "comment", text: "── パイプ2: grep → wc ──" },
        { op: "pipe", pid: 2 },
        { op: "comment", text: "── fork ls (stdout→pipe1 write) ──" },
        { op: "fork", parentPid: 2, childName: "ls" },
        { op: "exec", pid: 3, path: "/bin/ls", argv: [] },
        { op: "comment", text: "── fork grep (stdin←pipe1 read, stdout→pipe2 write) ──" },
        { op: "fork", parentPid: 2, childName: "grep" },
        { op: "exec", pid: 4, path: "/bin/grep", argv: ["pattern"] },
        { op: "comment", text: "── fork wc (stdin←pipe2 read) ──" },
        { op: "fork", parentPid: 2, childName: "wc" },
        { op: "exec", pid: 5, path: "/bin/wc", argv: ["-l"] },
        { op: "comment", text: "── ls がディレクトリ一覧をpipe1に書き込み ──" },
        { op: "write", pid: 3, fd: 1, data: "bin\ndev\netc\ntmp\nusr\n" },
        { op: "comment", text: "── grep がpipe1から読み取り、フィルタしてpipe2に書き込み ──" },
        { op: "read", pid: 4, fd: 0, size: 256 },
        { op: "write", pid: 4, fd: 3, data: "bin\n" },
        { op: "comment", text: "── wc がpipe2から読み取り、行数カウント ──" },
        { op: "read", pid: 5, fd: 2, size: 256 },
        { op: "comment", text: "── 各プロセスが順番に終了 ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "exit", pid: 4, code: 0 },
        { op: "exit", pid: 5, code: 0 },
        { op: "wait", pid: 2 },
        { op: "wait", pid: 2 },
        { op: "wait", pid: 2 },
        { op: "schedule" },
      ],
    }),
  },
  {
    name: "ゾンビ蓄積",
    description: "親がwait()を呼ばないと子プロセスがゾンビとして蓄積する問題を観察",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 親(sh)が3つの子をforkするが、waitしない ──" },
        { op: "fork", parentPid: 2, childName: "cmd1" },
        { op: "fork", parentPid: 2, childName: "cmd2" },
        { op: "fork", parentPid: 2, childName: "cmd3" },
        { op: "comment", text: "── 子プロセスが順番にexit → zombie化 ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "comment", text: "── cmd1 がゾンビに。procテーブルのスロットを消費 ──" },
        { op: "exit", pid: 4, code: 1 },
        { op: "comment", text: "── cmd2 もゾンビに。ゾンビが蓄積中 ──" },
        { op: "exit", pid: 5, code: 2 },
        { op: "comment", text: "── cmd3 もゾンビに。3つのゾンビがprocテーブルを占有 ──" },
        { op: "schedule" },
        { op: "comment", text: "── ようやくwait: ゾンビを1つ回収 ──" },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── まだ2つのゾンビが残っている ──" },
        { op: "wait", pid: 2 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── 全ゾンビ回収完了。教訓: waitを忘れるとリソースリーク ──" },
      ],
    }),
  },
  {
    name: "孤児プロセスのinit再配置",
    description: "親が先にexitすると子プロセス(孤児)がinit(PID 1)に引き取られる",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── sh が2つの子プロセスをfork ──" },
        { op: "fork", parentPid: 2, childName: "worker1" },
        { op: "fork", parentPid: 2, childName: "worker2" },
        { op: "comment", text: "── worker1, worker2 の ppid=2 (sh) ──" },
        { op: "schedule" },
        { op: "comment", text: "── 親(sh)が先に終了。子プロセスは孤児になる ──" },
        { op: "exit", pid: 2, code: 0 },
        { op: "comment", text: "── カーネルが孤児を検出 → ppid を 1 (init) に変更 ──" },
        { op: "comment", text: "── init が sh のゾンビを回収 ──" },
        { op: "wait", pid: 1 },
        { op: "comment", text: "── worker1, worker2 は init の子として継続実行 ──" },
        { op: "schedule" },
        { op: "comment", text: "── worker1 が終了 → init が回収 ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 1 },
        { op: "comment", text: "── worker2 が終了 → init が回収 ──" },
        { op: "exit", pid: 4, code: 0 },
        { op: "wait", pid: 1 },
        { op: "comment", text: "── 全プロセス回収完了。initは孤児の最終的な親 ──" },
      ],
    }),
  },
  {
    name: "fork後のfd共有",
    description: "fork()後の親子がファイルオフセットを共有する挙動を観察",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── sh がファイルをopen ──" },
        { op: "creat", pid: 2, path: "/tmp/shared.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "AAAA" },
        { op: "write", pid: 2, fd: 0, data: "BBBB" },
        { op: "write", pid: 2, fd: 0, data: "CCCC" },
        { op: "close", pid: 2, fd: 0 },
        { op: "open", pid: 2, path: "/tmp/shared.txt", mode: "read" },
        { op: "comment", text: "── fork: 子は親と同じsysfileエントリを共有 ──" },
        { op: "fork", parentPid: 2, childName: "child" },
        { op: "comment", text: "── 親がread → オフセットが進む ──" },
        { op: "read", pid: 2, fd: 0, size: 4 },
        { op: "comment", text: "── 子がread → 親のread分だけオフセットが進んでいる ──" },
        { op: "read", pid: 3, fd: 0, size: 4 },
        { op: "comment", text: "── 親がもう一度read → 子のread分もスキップ ──" },
        { op: "read", pid: 2, fd: 0, size: 4 },
        { op: "comment", text: "── これがV6の3層テーブル設計の効果 ──" },
        { op: "comment", text: "── fork: fdテーブルはコピー、sysfileは共有(refCount++) ──" },
        { op: "close", pid: 2, fd: 0 },
        { op: "close", pid: 3, fd: 0 },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
      ],
    }),
  },
  {
    name: "オープン中のファイル削除",
    description: "unlink後もオープン中のfdから読み書き可能。close時に実際に解放される",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── ファイルを作成して書き込み ──" },
        { op: "creat", pid: 2, path: "/tmp/ephemeral.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "This data will outlive the filename" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── ファイルを読み取り用にopen ──" },
        { op: "open", pid: 2, path: "/tmp/ephemeral.txt", mode: "read" },
        { op: "comment", text: "── unlink: ディレクトリエントリを削除 ──" },
        { op: "unlink", pid: 2, path: "/tmp/ephemeral.txt" },
        { op: "comment", text: "── ファイル名は消えたが、inode は fd 経由で参照中 ──" },
        { op: "comment", text: "── nlink=0 だが refCount>0 なので inode は解放されない ──" },
        { op: "stat", pid: 2, path: "/tmp/ephemeral.txt" },
        { op: "comment", text: "── 既に開いているfdからはまだ読み取り可能 ──" },
        { op: "read", pid: 2, fd: 0, size: 128 },
        { op: "comment", text: "── close: 最後の参照が消え、ここで初めてinode解放 ──" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── V6の遅延解放: UNIXの重要な設計原則 ──" },
      ],
    }),
  },
  {
    name: "I/Oリダイレクション (dup)",
    description: "dup()でfdを複製し、標準出力をファイルにリダイレクトするシェルの仕組み",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── シェルが 'cmd > output.txt' を実行する過程 ──" },
        { op: "comment", text: "── 1. 出力先ファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/tmp/output.txt", perm: 0o644 },
        { op: "comment", text: "── 2. fork: 子プロセスでリダイレクション設定 ──" },
        { op: "fork", parentPid: 2, childName: "cmd" },
        { op: "comment", text: "── 3. 子プロセスで dup: fd=0 を複製 → 新しいfdが割り当てられる ──" },
        { op: "dup", pid: 3, fd: 0 },
        { op: "comment", text: "── dup後: 2つのfdが同じsysfileエントリを指す ──" },
        { op: "comment", text: "── 実際のシェルでは close(1) → dup(fd) で stdout を差し替える ──" },
        { op: "comment", text: "── 4. 子プロセスが出力ファイルに書き込み ──" },
        { op: "write", pid: 3, fd: 0, data: "redirected output line 1\n" },
        { op: "write", pid: 3, fd: 0, data: "redirected output line 2\n" },
        { op: "comment", text: "── 5. 子プロセス終了、親がwait ──" },
        { op: "close", pid: 3, fd: 0 },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── 親プロセスで結果を確認 ──" },
        { op: "close", pid: 2, fd: 0 },
        { op: "open", pid: 2, path: "/tmp/output.txt", mode: "read" },
        { op: "read", pid: 2, fd: 0, size: 256 },
        { op: "close", pid: 2, fd: 0 },
      ],
    }),
  },
  {
    name: "プロセス優先度とnice",
    description: "nice値の変更がスケジューリング優先度に与える影響を観察",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 3つのプロセスを起動 ──" },
        { op: "fork", parentPid: 2, childName: "batch" },
        { op: "fork", parentPid: 2, childName: "interactive" },
        { op: "fork", parentPid: 2, childName: "background" },
        { op: "comment", text: "── nice値を設定: 優先度を差別化 ──" },
        { op: "nice", pid: 3, value: 10 },
        { op: "comment", text: "── batch: nice=10 (低優先度、バッチジョブ向き) ──" },
        { op: "nice", pid: 4, value: -5 },
        { op: "comment", text: "── interactive: nice=-5 (高優先度、対話型向き) ──" },
        { op: "nice", pid: 5, value: 20 },
        { op: "comment", text: "── background: nice=20 (最低優先度) ──" },
        { op: "comment", text: "── スケジューリング: priority = cpuUsage/2 + PUSER + nice ──" },
        { op: "schedule" },
        { op: "comment", text: "── nice=-5 の interactive が最初に選ばれる ──" },
        { op: "schedule" },
        { op: "comment", text: "── CPU使用量の減衰により優先度が再計算される ──" },
        { op: "schedule" },
        { op: "comment", text: "── V6のスケジューラは「多段フィードバックキュー」の変形 ──" },
        { op: "comment", text: "── nice(2)は一般ユーザーは正の値のみ(自分を低優先度に)設定可能 ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "exit", pid: 4, code: 0 },
        { op: "exit", pid: 5, code: 0 },
        { op: "wait", pid: 2 },
        { op: "wait", pid: 2 },
        { op: "wait", pid: 2 },
      ],
    }),
  },
  {
    name: "デーモンプロセス (ダブルfork)",
    description: "デーモン化のダブルforkパターン: 端末から完全に切り離す",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── デーモンの起動パターン (cron等) ──" },
        { op: "comment", text: "── 1st fork: 親(sh)はすぐにwaitで回収 ──" },
        { op: "fork", parentPid: 2, childName: "daemon-helper" },
        { op: "comment", text: "── 中間プロセスがさらにfork ──" },
        { op: "fork", parentPid: 3, childName: "daemon" },
        { op: "comment", text: "── 2nd fork: 中間プロセスが即exit ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "comment", text: "── 中間プロセスのexit → daemon は孤児 → init が親に ──" },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── sh は中間プロセスを回収。daemon は init の子 ──" },
        { op: "wait", pid: 1 },
        { op: "comment", text: "── daemon (PID 4) は init の子として独立して実行 ──" },
        { op: "comment", text: "── 端末を閉じても SIGHUP が daemon に届かない ──" },
        { op: "exec", pid: 4, path: "/etc/cron", argv: [] },
        { op: "comment", text: "── daemon がバックグラウンドタスクを実行 ──" },
        { op: "creat", pid: 4, path: "/tmp/cron.log", perm: 0o644 },
        { op: "write", pid: 4, fd: 0, data: "cron: running scheduled task\n" },
        { op: "close", pid: 4, fd: 0 },
        { op: "schedule" },
        { op: "comment", text: "── ダブルforkにより: (1)ゾンビなし (2)端末独立 (3)init回収 ──" },
      ],
    }),
  },
  {
    name: "ハードリンクとinode共有",
    description: "1つのファイルに複数の名前をつける。link/unlinkとnlinkの関係",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── ファイルを作成 (nlink=1) ──" },
        { op: "creat", pid: 2, path: "/tmp/original.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "shared content via hard link" },
        { op: "close", pid: 2, fd: 0 },
        { op: "stat", pid: 2, path: "/tmp/original.txt" },
        { op: "comment", text: "── link: 同じinodeに新しい名前をつける ──" },
        { op: "link", pid: 2, existingPath: "/tmp/original.txt", newPath: "/tmp/alias1.txt" },
        { op: "comment", text: "── nlink=2: 2つのディレクトリエントリが同じinodeを指す ──" },
        { op: "stat", pid: 2, path: "/tmp/original.txt" },
        { op: "comment", text: "── さらにlinkを追加 ──" },
        { op: "link", pid: 2, existingPath: "/tmp/original.txt", newPath: "/tmp/alias2.txt" },
        { op: "comment", text: "── nlink=3: 3つの名前が同一ファイル ──" },
        { op: "stat", pid: 2, path: "/tmp/alias1.txt" },
        { op: "comment", text: "── alias1経由で読んでもoriginal経由で読んでも同じデータ ──" },
        { op: "open", pid: 2, path: "/tmp/alias2.txt", mode: "read" },
        { op: "read", pid: 2, fd: 0, size: 128 },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── unlink original: nlink=2 (ファイルはまだ存在) ──" },
        { op: "unlink", pid: 2, path: "/tmp/original.txt" },
        { op: "stat", pid: 2, path: "/tmp/alias1.txt" },
        { op: "comment", text: "── unlink alias1: nlink=1 ──" },
        { op: "unlink", pid: 2, path: "/tmp/alias1.txt" },
        { op: "comment", text: "── unlink alias2: nlink=0 → ここで初めてinode解放 ──" },
        { op: "unlink", pid: 2, path: "/tmp/alias2.txt" },
        { op: "comment", text: "── V6のinode方式: ファイル名はinodeの「別名」に過ぎない ──" },
      ],
    }),
  },
  {
    name: "cat コマンド",
    description: "最もシンプルなUnixコマンド: open→read→write(stdout)→close のシステムコール分解",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 表示対象のファイルを準備 ──" },
        { op: "creat", pid: 2, path: "/etc/motd", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "Welcome to Unix V6\n" },
        { op: "write", pid: 2, fd: 0, data: "PDP-11/40, 64KB RAM\n" },
        { op: "write", pid: 2, fd: 0, data: "Bell Laboratories\n" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── $ cat /etc/motd ──" },
        { op: "comment", text: "── sh: fork → 子プロセスで exec /bin/cat ──" },
        { op: "fork", parentPid: 2, childName: "cat" },
        { op: "exec", pid: 3, path: "/bin/cat", argv: ["/etc/motd"] },
        { op: "comment", text: "── cat の中身: open(argv[1], 0) ──" },
        { op: "open", pid: 3, path: "/etc/motd", mode: "read" },
        { op: "comment", text: "── cat: read ループ (EOF まで繰り返す) ──" },
        { op: "read", pid: 3, fd: 0, size: 512 },
        { op: "comment", text: "── cat: read した内容を stdout (fd=1) に write ──" },
        { op: "comment", text: "── (このシミュレータではfd=1の模擬は省略) ──" },
        { op: "comment", text: "── cat: EOF → close してexit ──" },
        { op: "close", pid: 3, fd: 0 },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── cat は UNIX哲学の原点: 1つのことをうまくやる ──" },
        { op: "comment", text: "── V6の cat.c はわずか30行 (Lions' Commentary 参照) ──" },
      ],
    }),
  },
  {
    name: "cp コマンド",
    description: "ファイルコピーのシステムコール分解: open(src)→creat(dst)→read/writeループ",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── コピー元ファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/tmp/src.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "first block data " + "A".repeat(400) },
        { op: "write", pid: 2, fd: 0, data: "second block data " + "B".repeat(400) },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── $ cp /tmp/src.txt /tmp/dst.txt ──" },
        { op: "fork", parentPid: 2, childName: "cp" },
        { op: "exec", pid: 3, path: "/bin/cp", argv: ["/tmp/src.txt", "/tmp/dst.txt"] },
        { op: "comment", text: "── cp: open(src, O_RDONLY) ──" },
        { op: "open", pid: 3, path: "/tmp/src.txt", mode: "read" },
        { op: "comment", text: "── cp: creat(dst, perm) — 新しいinodeが割り当てられる ──" },
        { op: "creat", pid: 3, path: "/tmp/dst.txt", perm: 0o644 },
        { op: "comment", text: "── cp: read(src) → write(dst) ループ (512バイト単位) ──" },
        { op: "read", pid: 3, fd: 0, size: 512 },
        { op: "write", pid: 3, fd: 1, data: "first block data " + "A".repeat(400) },
        { op: "comment", text: "── 2ブロック目 ──" },
        { op: "read", pid: 3, fd: 0, size: 512 },
        { op: "write", pid: 3, fd: 1, data: "second block data " + "B".repeat(400) },
        { op: "comment", text: "── cp: close(src), close(dst) ──" },
        { op: "close", pid: 3, fd: 0 },
        { op: "close", pid: 3, fd: 1 },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── コピー結果を確認: 別のinodeだがデータは同一 ──" },
        { op: "stat", pid: 2, path: "/tmp/src.txt" },
        { op: "stat", pid: 2, path: "/tmp/dst.txt" },
        { op: "comment", text: "── cp vs link: cpは独立コピー、linkはinode共有 ──" },
      ],
    }),
  },
  {
    name: "mv コマンド (同一FS内)",
    description: "link(新名前)→unlink(旧名前)で実現。データコピーは不要",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 移動対象のファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/tmp/old_name.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "This file will be renamed" },
        { op: "close", pid: 2, fd: 0 },
        { op: "stat", pid: 2, path: "/tmp/old_name.txt" },
        { op: "comment", text: "── $ mv /tmp/old_name.txt /tmp/new_name.txt ──" },
        { op: "fork", parentPid: 2, childName: "mv" },
        { op: "exec", pid: 3, path: "/bin/mv", argv: ["/tmp/old_name.txt", "/tmp/new_name.txt"] },
        { op: "comment", text: "── mv の実装: link(old, new) → unlink(old) ──" },
        { op: "comment", text: "── Step 1: link — 同じinodeに新しい名前をつける ──" },
        { op: "link", pid: 3, existingPath: "/tmp/old_name.txt", newPath: "/tmp/new_name.txt" },
        { op: "comment", text: "── nlink=2: 一時的に両方の名前が存在する ──" },
        { op: "comment", text: "── Step 2: unlink — 古い名前を削除 ──" },
        { op: "unlink", pid: 3, path: "/tmp/old_name.txt" },
        { op: "comment", text: "── nlink=1: 新しい名前だけが残る。inode番号は同じ ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── stat で確認: inode番号が変わっていない ──" },
        { op: "stat", pid: 2, path: "/tmp/new_name.txt" },
        { op: "comment", text: "── mvの利点: データブロックのコピーが一切不要 ──" },
        { op: "comment", text: "── ただし別FSへのmvはcp+unlinkが必要(V6のmv.cで実装) ──" },
      ],
    }),
  },
  {
    name: "シェルスクリプト実行",
    description: "sh がスクリプトの各行を fork/exec/wait で逐次実行する過程",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── シェルスクリプト /tmp/setup.sh の内容: ──" },
        { op: "comment", text: "──   mkdir /usr/local              ──" },
        { op: "comment", text: "──   cp /etc/motd /tmp/motd.bak    ──" },
        { op: "comment", text: "──   echo done                     ──" },
        { op: "creat", pid: 2, path: "/tmp/setup.sh", perm: 0o755 },
        { op: "write", pid: 2, fd: 0, data: "mkdir /usr/local\ncp /etc/motd /tmp/motd.bak\necho done\n" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── $ sh /tmp/setup.sh ──" },
        { op: "comment", text: "── sh: スクリプトを1行ずつ読んで実行 ──" },
        { op: "open", pid: 2, path: "/tmp/setup.sh", mode: "read" },
        { op: "read", pid: 2, fd: 0, size: 512 },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── 行1: mkdir /usr/local ──" },
        { op: "fork", parentPid: 2, childName: "mkdir" },
        { op: "exec", pid: 3, path: "/bin/mkdir", argv: ["/usr/local"] },
        { op: "mkdir", pid: 3, path: "/usr/local" },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── 行2: cp (open→creat→read/write→close) ──" },
        { op: "fork", parentPid: 2, childName: "cp" },
        { op: "exec", pid: 4, path: "/bin/cp", argv: ["/etc/motd", "/tmp/motd.bak"] },
        { op: "creat", pid: 4, path: "/tmp/motd.bak", perm: 0o644 },
        { op: "write", pid: 4, fd: 0, data: "backup of motd" },
        { op: "close", pid: 4, fd: 0 },
        { op: "exit", pid: 4, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── 行3: echo done (組み込みコマンド、forkしない) ──" },
        { op: "comment", text: "── シェルの基本ループ: read line → parse → fork/exec/wait ──" },
        { op: "comment", text: "── V6の sh.c は約900行。パイプ/リダイレクト/&/if/goto対応 ──" },
      ],
    }),
  },
  {
    name: "バックグラウンド実行 (&)",
    description: "シェルの & 構文: fork後にwaitせず次のコマンドに進む",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── $ long_task & ──" },
        { op: "comment", text: "── sh: fork するが wait しない → プロンプトに即戻る ──" },
        { op: "fork", parentPid: 2, childName: "long_task" },
        { op: "exec", pid: 3, path: "/usr/bin/long_task", argv: [] },
        { op: "comment", text: "── sh: 'PID 3' を表示してプロンプトに戻る ──" },
        { op: "comment", text: "── long_task がバックグラウンドで動作中... ──" },
        { op: "creat", pid: 3, path: "/tmp/result.txt", perm: 0o644 },
        { op: "write", pid: 3, fd: 0, data: "long computation result\n" },
        { op: "schedule" },
        { op: "comment", text: "── $ another_cmd (フォアグラウンド実行) ──" },
        { op: "fork", parentPid: 2, childName: "another_cmd" },
        { op: "exec", pid: 4, path: "/bin/echo", argv: ["hello"] },
        { op: "comment", text: "── sh: フォアグラウンドのコマンドは wait する ──" },
        { op: "exit", pid: 4, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── another_cmd 完了。long_task はまだ実行中 ──" },
        { op: "schedule" },
        { op: "comment", text: "── long_task が完了 ──" },
        { op: "close", pid: 3, fd: 0 },
        { op: "exit", pid: 3, code: 0 },
        { op: "comment", text: "── long_task はゾンビに。sh が次にwaitすると回収される ──" },
        { op: "comment", text: "── V6のshでは & で起動したプロセスのSIGINT/SIGQUITを無視設定 ──" },
        { op: "signal", pid: 3, sig: "SIGINT", action: "ignore" },
        { op: "signal", pid: 3, sig: "SIGQUIT", action: "ignore" },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── &の仕組み: waitを呼ばないだけ。シンプルだが強力 ──" },
      ],
    }),
  },
  {
    name: "同時書き込み競合",
    description: "2プロセスが同じファイルに書き込む際のV6の挙動と問題点",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 共有ログファイルを作成 ──" },
        { op: "creat", pid: 2, path: "/tmp/log.txt", perm: 0o666 },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── 2つのプロセスが同じファイルを独立にopen ──" },
        { op: "fork", parentPid: 2, childName: "writer1" },
        { op: "fork", parentPid: 2, childName: "writer2" },
        { op: "comment", text: "── 各プロセスが独立にopen → 別々のsysfileエントリ ──" },
        { op: "comment", text: "── つまりオフセットも独立 → 上書き競合の原因 ──" },
        { op: "open", pid: 3, path: "/tmp/log.txt", mode: "write" },
        { op: "open", pid: 4, path: "/tmp/log.txt", mode: "write" },
        { op: "comment", text: "── writer1 が書き込み (offset=0) ──" },
        { op: "write", pid: 3, fd: 0, data: "writer1: log entry AAA\n" },
        { op: "comment", text: "── writer2 も書き込み (offset=0!) → writer1のデータを上書き ──" },
        { op: "write", pid: 4, fd: 0, data: "writer2: log entry BBB\n" },
        { op: "comment", text: "── 問題: 独立openは独立offset → データ破壊 ──" },
        { op: "write", pid: 3, fd: 0, data: "writer1: second line\n" },
        { op: "write", pid: 4, fd: 0, data: "writer2: second line\n" },
        { op: "close", pid: 3, fd: 0 },
        { op: "close", pid: 4, fd: 0 },
        { op: "comment", text: "── 対策1: fork前にopen → sysfile共有でoffsetが進む ──" },
        { op: "comment", text: "── 対策2: V7以降の O_APPEND フラグ (書き込み前にseek末尾) ──" },
        { op: "comment", text: "── 対策3: flock()/lockf() でファイルロック (V6には未実装) ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "exit", pid: 4, code: 0 },
        { op: "wait", pid: 2 },
        { op: "wait", pid: 2 },
      ],
    }),
  },
  {
    name: "chmod と権限管理",
    description: "V6のパーミッションビット(rwx)の変更とsetuidの仕組み",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── ファイルを作成 (デフォルト 644: rw-r--r--) ──" },
        { op: "creat", pid: 2, path: "/tmp/script.sh", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "#!/bin/sh\necho hello\n" },
        { op: "close", pid: 2, fd: 0 },
        { op: "stat", pid: 2, path: "/tmp/script.sh" },
        { op: "comment", text: "── chmod 755: 実行権限を付与 (rwxr-xr-x) ──" },
        { op: "chmod", pid: 2, path: "/tmp/script.sh", mode: 0o100755 },
        { op: "stat", pid: 2, path: "/tmp/script.sh" },
        { op: "comment", text: "── V6のモードビット構造: ──" },
        { op: "comment", text: "──   [ファイル種別 4bit][suid/sgid/sticky 3bit][rwx×3 9bit] ──" },
        { op: "comment", text: "── 秘密ファイル: chmod 600 (rw-------) ──" },
        { op: "creat", pid: 2, path: "/tmp/secret.txt", perm: 0o600 },
        { op: "write", pid: 2, fd: 0, data: "confidential data" },
        { op: "close", pid: 2, fd: 0 },
        { op: "stat", pid: 2, path: "/tmp/secret.txt" },
        { op: "comment", text: "── ディレクトリの権限: rwx の意味が異なる ──" },
        { op: "comment", text: "──   r: ディレクトリ内のファイル一覧を読める ──" },
        { op: "comment", text: "──   w: ファイルの作成/削除ができる ──" },
        { op: "comment", text: "──   x: ディレクトリを通過(パス解決)できる ──" },
        { op: "mkdir", pid: 2, path: "/tmp/restricted" },
        { op: "chmod", pid: 2, path: "/tmp/restricted", mode: 0o040700 },
        { op: "stat", pid: 2, path: "/tmp/restricted" },
        { op: "comment", text: "── setuid ビット (04000): 実行時にファイル所有者の権限で動作 ──" },
        { op: "comment", text: "── passwd コマンドが /etc/passwd を書き換えられる理由 ──" },
        { op: "chmod", pid: 2, path: "/tmp/script.sh", mode: 0o104755 },
        { op: "stat", pid: 2, path: "/tmp/script.sh" },
        { op: "comment", text: "── V6の権限チェック: UID→所有者→グループ→その他の順 ──" },
      ],
    }),
  },
  {
    name: "スワッピングサブシステム",
    description: "メモリ不足時のスワップアウト/イン。テキストセグメント共有による省メモリ",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── V6のスワッピング (slp.c: sched) ──" },
        { op: "comment", text: "── PDP-11は64KBの物理メモリ。複数プロセスを動かすにはスワップが必須 ──" },
        { op: "comment", text: "── テキストセグメント共有 (xalloc): 同じ実行ファイルのコードを共有 ──" },
        { op: "fork", parentPid: 2, childName: "proc1" },
        { op: "exec", pid: 3, path: "/bin/sh", argv: ["proc1"] },
        { op: "xalloc", pid: 3, path: "/bin/sh" },
        { op: "comment", text: "── proc1 が /bin/sh のテキストを取得 (新規割当) ──" },
        { op: "fork", parentPid: 2, childName: "proc2" },
        { op: "exec", pid: 4, path: "/bin/sh", argv: ["proc2"] },
        { op: "xalloc", pid: 4, path: "/bin/sh" },
        { op: "comment", text: "── proc2 も /bin/sh → テキスト共有 (refCount++) ──" },
        { op: "comment", text: "── メモリ不足発生 → スワッパがproc1をスワップアウト ──" },
        { op: "swap_out", pid: 3 },
        { op: "comment", text: "── xccdec: テキストのコアカウントが減少 (コード共有は継続) ──" },
        { op: "schedule" },
        { op: "comment", text: "── proc1 を再度メモリに読み込み ──" },
        { op: "swap_in", pid: 3 },
        { op: "comment", text: "── xalloc(swap_in): テキストのコアカウントが復帰 ──" },
        { op: "schedule" },
        { op: "comment", text: "── テキスト解放: proc1 終了 → xfree (refCount--) ──" },
        { op: "xfree", pid: 3 },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── proc2 終了 → 最後の参照解放でテキストエントリ削除 ──" },
        { op: "xfree", pid: 4 },
        { op: "exit", pid: 4, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── V6のスワッパはPID 0。常にカーネルモードで動作 ──" },
      ],
    }),
  },
  {
    name: "TTY端末入出力",
    description: "キャラクタI/O: clist、rawq/canq/outq、canon処理、特殊文字",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── V6の端末I/O (tty.c, kl.c) ──" },
        { op: "comment", text: "── 3つのキュー: rawq(生入力), canq(正規入力), outq(出力) ──" },
        { op: "comment", text: "── 端末入力は割り込みドリブン: KL11が1文字受信するたびに割り込み発生 ──" },
        { op: "tty_input", device: 0, chars: "l" },
        { op: "tty_input", device: 0, chars: "s" },
        { op: "tty_input", device: 0, chars: "\n" },
        { op: "comment", text: "── 改行で canon() 処理: rawq→canq に移動。プロセスのread()が完了 ──" },
        { op: "comment", text: "── 消去文字 '#' (V6独特の仕様) で1文字削除 ──" },
        { op: "tty_input", device: 0, chars: "c" },
        { op: "tty_input", device: 0, chars: "t" },
        { op: "tty_input", device: 0, chars: "#" },
        { op: "comment", text: "── '#' で 't' が消去され、rawq は 'c' のみ ──" },
        { op: "tty_input", device: 0, chars: "a" },
        { op: "tty_input", device: 0, chars: "t" },
        { op: "tty_input", device: 0, chars: "\n" },
        { op: "comment", text: "── 結果: 'cat' が canq に入る ──" },
        { op: "comment", text: "── 行削除文字 '@' で行全体を消去 ──" },
        { op: "tty_input", device: 0, chars: "wrong_command" },
        { op: "tty_input", device: 0, chars: "@" },
        { op: "comment", text: "── rawq がクリアされ、入力をやり直せる ──" },
        { op: "tty_input", device: 0, chars: "correct\n" },
        { op: "comment", text: "── 端末出力: プロセスのwrite()がoutqに入り、出力割り込みで送信 ──" },
        { op: "tty_output", pid: 2, device: 0, chars: "$ " },
        { op: "tty_output", pid: 2, device: 0, chars: "hello world\n" },
        { op: "comment", text: "── stty: 端末設定変更 ──" },
        { op: "tty_ioctl", pid: 2, device: 0, cmd: "echo" },
        { op: "comment", text: "── ECHO OFF: パスワード入力時など ──" },
        { op: "tty_ioctl", pid: 2, device: 0, cmd: "echo" },
        { op: "comment", text: "── ECHO ON に戻す ──" },
        { op: "tty_ioctl", pid: 2, device: 0, cmd: "raw" },
        { op: "comment", text: "── RAWモード: ライン規約バイパス。1文字ずつ即座にプロセスに届く ──" },
        { op: "tty_input", device: 0, chars: "x" },
        { op: "comment", text: "── RAWモードでは canon 処理をスキップし直接 canq に入る ──" },
        { op: "tty_ioctl", pid: 2, device: 0, cmd: "raw" },
        { op: "comment", text: "── 正規モードに戻す ──" },
        { op: "comment", text: "── V6のclist: 6文字単位のcblockで可変長キューを実現 ──" },
      ],
    }),
  },
  {
    name: "割り込みとトラップ機構",
    description: "PDP-11のベクタ割り込み、trap命令によるsyscall、sysent[]ディスパッチ",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── PDP-11の割り込み/トラップ機構 ──" },
        { op: "comment", text: "── 割り込みベクタ: アドレス0番地から配置される(PC, PSW)ペア ──" },
        { op: "comment", text: "── 0000: バスエラー  0004: 不正命令  0030: TRAP(syscall) ──" },
        { op: "comment", text: "── 0060: クロック    0220: RK11ディスク  0100: KL11端末 ──" },
        { op: "comment", text: "── 割り込み優先レベル: BR7(最高)→BR4(最低) ──" },
        { op: "comment", text: "── システムコール呼び出しの流れ: ──" },
        { op: "comment", text: "──   1. ユーザープログラムが trap 命令を実行 ──" },
        { op: "comment", text: "──   2. PDP-11がPSW/PCをスタックに保存、ベクタ030のPC/PSWをロード ──" },
        { op: "comment", text: "──   3. trap()ハンドラが r0 からsyscall番号を取得 ──" },
        { op: "comment", text: "──   4. sysent[r0] でカーネル関数をディスパッチ ──" },
        { op: "comment", text: "──   5. カーネル関数実行後、RTI命令でユーザーモードに復帰 ──" },
        { op: "comment", text: "── 例: open() syscall (番号5) ──" },
        { op: "open", pid: 2, path: "/etc/rc", mode: "read" },
        { op: "comment", text: "── ↑ [trap] entry→kernel mode → sysent[5].handler='open' → return→user mode ──" },
        { op: "read", pid: 2, fd: 0, size: 128 },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── クロック割り込み (ベクタ060, BR6): 毎秒60回 ──" },
        { op: "comment", text: "── clock()ハンドラ: CPU使用量加算、アラーム処理、runrunフラグ設定 ──" },
        { op: "schedule" },
        { op: "comment", text: "── [intr] clock tick → cpuUsage++、priority再計算、必要ならswtch() ──" },
        { op: "comment", text: "── RK11ディスク割り込み (ベクタ0220, BR5): ──" },
        { op: "dev_strategy", device: 0, blockNum: 42, write: false },
        { op: "dev_interrupt", device: 0 },
        { op: "comment", text: "── strategy()→start()→[DMA転送]→割り込み→iodone()→brelse() ──" },
        { op: "comment", text: "── KL11端末割り込み (ベクタ0100, BR4): ──" },
        { op: "tty_input", device: 0, chars: "test\n" },
        { op: "comment", text: "── 端末受信割り込み → klrint() → ttyinput() → rawq追加 ──" },
      ],
    }),
  },
  {
    name: "ブロックデバイスドライバ (RK11)",
    description: "bdevsw[]テーブル、strategy/start/interrupt パターン、バッファキャッシュ連携",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── V6のブロックデバイスドライバ (rk.c) ──" },
        { op: "comment", text: "── bdevsw[]: デバイス番号→ドライバ関数のマッピングテーブル ──" },
        { op: "comment", text: "──   bdevsw[0] = { rkopen, nulldev, rkstrategy } (RK05ディスク) ──" },
        { op: "comment", text: "──   bdevsw[1] = { rpopen, nulldev, rpstrategy } (RP03ディスク) ──" },
        { op: "comment", text: "── I/Oの3フェーズ: ──" },
        { op: "comment", text: "──   1. strategy(bp): I/O要求をデバイスキューに投入 ──" },
        { op: "comment", text: "──   2. start(): 物理デバイスのDMA転送を開始 ──" },
        { op: "comment", text: "──   3. interrupt(): 転送完了 → iodone() → brelse() ──" },
        { op: "comment", text: "── RK05ディスクパック: 2.5MB, 4872ブロック ──" },
        { op: "comment", text: "── ブロック読み込み: bread()→getblk()→rkstrategy()→start() ──" },
        { op: "dev_strategy", device: 0, blockNum: 100, write: false },
        { op: "dev_interrupt", device: 0 },
        { op: "comment", text: "── ブロック書き込み: bwrite()→rkstrategy()→start() ──" },
        { op: "dev_strategy", device: 0, blockNum: 100, write: true },
        { op: "dev_interrupt", device: 0 },
        { op: "comment", text: "── 実際のファイルI/O経由のデバイスアクセス ──" },
        { op: "creat", pid: 2, path: "/tmp/devtest", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "data through buffer cache → device driver" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── write → バッファキャッシュ → dirty → sync → strategy → DMA ──" },
        { op: "sync" },
        { op: "comment", text: "── syncでdirtyバッファが全てdevice driverを通じてディスクに書き戻される ──" },
        { op: "comment", text: "── cdevsw[]: キャラクタデバイスのスイッチテーブル ──" },
        { op: "comment", text: "──   cdevsw[0] = { klopen, klclose, klread, klwrite } (コンソール) ──" },
        { op: "comment", text: "──   cdevsw[2] = { lpopen, lpclose, nodev, lpwrite } (プリンタ) ──" },
      ],
    }),
  },
  {
    name: "パーミッションとSUID",
    description: "V6のuid/gid/modeによるアクセス制御、SUID/SGIDビットの動作",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── V6のパーミッションシステム (fio.c: access) ──" },
        { op: "comment", text: "── モードビット: [ファイル種別 4bit][suid/sgid/sticky 3bit][rwx×3 9bit] ──" },
        { op: "comment", text: "── アクセスチェック順序: uid=0 → owner → group → other ──" },
        { op: "comment", text: "── uid=0(root)は全アクセス許可 (suser() in sys4.c) ──" },
        { op: "creat", pid: 2, path: "/tmp/public.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "public data" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── 644 (rw-r--r--): 所有者=rw, グループ=r, その他=r ──" },
        { op: "creat", pid: 2, path: "/tmp/secret.txt", perm: 0o600 },
        { op: "write", pid: 2, fd: 0, data: "secret data" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── 600 (rw-------): 所有者のみ読み書き可能 ──" },
        { op: "creat", pid: 2, path: "/tmp/exec_test", perm: 0o755 },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── 755 (rwxr-xr-x): 全ユーザーが実行可能 ──" },
        { op: "comment", text: "── setuid ビット (04000): exec時にファイル所有者のUIDに切り替え ──" },
        { op: "comment", text: "── 例: /bin/passwd は SUID root。一般ユーザーが /etc/passwd を書き換え可能 ──" },
        { op: "chmod", pid: 2, path: "/tmp/exec_test", mode: 0o104755 },
        { op: "comment", text: "── 04755: SUID+rwxr-xr-x。実行するとUID 0で動作する ──" },
        { op: "stat", pid: 2, path: "/tmp/exec_test" },
        { op: "fork", parentPid: 2, childName: "suid_prog" },
        { op: "exec", pid: 3, path: "/tmp/exec_test", argv: ["suid_test"] },
        { op: "comment", text: "── exec時にSUIDビットを検出 → プロセスのuidがファイル所有者に変更 ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── V6のアクセスチェック: 実効UIDで判定。実UID≠実効UIDの場合がSUID ──" },
        { op: "comment", text: "── ディレクトリの権限: r=一覧読取, w=ファイル作成/削除, x=パス解決通過 ──" },
      ],
    }),
  },
  {
    name: "マウントとファイルシステム構造",
    description: "mount/umount、スーパーブロック、nameiのマウントポイント越え",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── V6のマウント (sys3.c: smount) ──" },
        { op: "comment", text: "── mount[]テーブル: 最大5つのFSを同時マウント (NMOUNT=5) ──" },
        { op: "comment", text: "── V6のディスクレイアウト: ──" },
        { op: "comment", text: "──   Block 0: ブートブロック (ブートローダ) ──" },
        { op: "comment", text: "──   Block 1: スーパーブロック (FSメタデータ) ──" },
        { op: "comment", text: "──   Block 2-17: inodeテーブル (256 inodes) ──" },
        { op: "comment", text: "──   Block 18+: データブロック ──" },
        { op: "mkdir", pid: 2, path: "/mnt" },
        { op: "comment", text: "── /dev/rk1 を /mnt にマウント ──" },
        { op: "mount", pid: 2, device: "/dev/rk1", path: "/mnt" },
        { op: "comment", text: "── mount: スーパーブロック読込、マウントテーブルにエントリ追加 ──" },
        { op: "comment", text: "── nameiがマウントポイントを越えるとm_bufp経由で別デバイスのFSに遷移 ──" },
        { op: "stat", pid: 2, path: "/mnt" },
        { op: "comment", text: "── 2つ目のFSをマウント ──" },
        { op: "mkdir", pid: 2, path: "/usr2" },
        { op: "mount", pid: 2, device: "/dev/rk2", path: "/usr2" },
        { op: "comment", text: "── umount: dirtyバッファ書き戻し → マウントテーブルから除去 ──" },
        { op: "umount", pid: 2, device: "/dev/rk2" },
        { op: "comment", text: "── アンマウント完了。/usr2 は空のディレクトリに戻る ──" },
        { op: "umount", pid: 2, device: "/dev/rk1" },
        { op: "comment", text: "── V6のルートFSはRK05ディスクパック (2.5MB, 4872ブロック) ──" },
      ],
    }),
  },
  {
    name: "sysent[]とシステムコールの内部構造",
    description: "V6の約50個のシステムコール、trap→sysent[]→カーネル関数のディスパッチ",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── V6のシステムコール一覧 (sysent.c) ──" },
        { op: "comment", text: "── 呼び出しの仕組み: ──" },
        { op: "comment", text: "──   1. ユーザー空間: sys fork (アセンブラマクロ) ──" },
        { op: "comment", text: "──   2. → trap命令 → ベクタ030 → trap()ハンドラ ──" },
        { op: "comment", text: "──   3. → r0レジスタからsyscall番号取得 ──" },
        { op: "comment", text: "──   4. → sysent[r0].call() でカーネル関数呼び出し ──" },
        { op: "comment", text: "──   5. → 結果をr0に格納、RTI命令でユーザーモード復帰 ──" },
        { op: "comment", text: "── 主要syscall: fork(2), read(3), write(4), open(5), close(6) ──" },
        { op: "comment", text: "──   wait(7), creat(8), link(9), unlink(10), exec(11) ──" },
        { op: "comment", text: "──   chdir(12), chmod(15), stat(18), seek(19), mount(21) ──" },
        { op: "comment", text: "──   signal(48), kill(37), pipe(42), dup(41), nice(34) ──" },
        { op: "comment", text: "── 実際のsyscallシーケンス: creat → write → close ──" },
        { op: "creat", pid: 2, path: "/tmp/syscall_demo", perm: 0o644 },
        { op: "comment", text: "── ↑ trap→sysent[8]→creat()→namei()→ialloc()→fd割当 ──" },
        { op: "write", pid: 2, fd: 0, data: "syscall demo data" },
        { op: "comment", text: "── ↑ trap→sysent[4]→rdwri()→bmap()→alloc()→バッファキャッシュ ──" },
        { op: "close", pid: 2, fd: 0 },
        { op: "comment", text: "── ↑ trap→sysent[6]→closef()→iput() ──" },
        { op: "comment", text: "── エラー時: u.u_errorにエラーコードを設定、carry flagを立ててreturn ──" },
        { op: "comment", text: "── V6のsyscallは約50個。Linux(300+)と比べるとコンパクト ──" },
      ],
    }),
  },
  {
    name: "端末割り込みとシグナル配送",
    description: "DELキー→SIGINT、Ctrl-\\→SIGQUIT、シグナル配送サイクル(psignal/issig/psig)",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── 端末割り込みからシグナル配送まで ──" },
        { op: "comment", text: "── V6のシグナル配送サイクル (sig.c): ──" },
        { op: "comment", text: "──   1. psignal(proc, sig): シグナルを保留リストに追加 ──" },
        { op: "comment", text: "──   2. issig(): syscall return時に保留シグナルをチェック ──" },
        { op: "comment", text: "──   3. psig(): シグナルを実際に配送 (default/ignore/catch) ──" },
        { op: "fork", parentPid: 2, childName: "daemon" },
        { op: "exec", pid: 3, path: "/bin/sh", argv: ["daemon"] },
        { op: "signal", pid: 3, sig: "SIGINT", action: "catch" },
        { op: "comment", text: "── daemonがSIGINTをcatch設定 ──" },
        { op: "comment", text: "── ユーザーが DEL キーを押す → 端末割り込み ──" },
        { op: "tty_input", device: 0, chars: "\x7f" },
        { op: "comment", text: "── klrint()→ttyinput()→SIGINTをpsignal()で配送 ──" },
        { op: "comment", text: "── daemonのpendingSignalsにSIGINTが追加される ──" },
        { op: "kill", senderPid: 1, targetPid: 3, sig: "SIGINT" },
        { op: "comment", text: "── issig()→psig()→ハンドラ実行 (ワンショット: 実行後DFLに戻る) ──" },
        { op: "comment", text: "── FS キー (Ctrl-\\) → SIGQUIT + コアダンプ ──" },
        { op: "fork", parentPid: 2, childName: "victim" },
        { op: "exec", pid: 4, path: "/bin/sh", argv: ["victim"] },
        { op: "tty_input", device: 0, chars: "\x1c" },
        { op: "comment", text: "── SIGQUIT: デフォルト動作は終了+コアダンプ ──" },
        { op: "kill", senderPid: 1, targetPid: 4, sig: "SIGQUIT" },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── V6のコアダンプ対象シグナル: SIGQUIT, SIGILL, SIGTRAP, SIGIOT, SIGEMT, SIGFPE, SIGBUS, SIGSEGV ──" },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
      ],
    }),
  },
  {
    name: "ブートシーケンス詳細",
    description: "start→main→binit→iinit→newproc→sched→init→getty→login→shell",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "comment", text: "── V6ブートシーケンス詳細 (m40.s, main.c) ──" },
        { op: "comment", text: "── 1. ブートブロック(blk 0)がカーネルをメモリにロード ──" },
        { op: "comment", text: "── 2. start: (m40.s) MMU初期化、スタック設定 ──" },
        { op: "comment", text: "── 3. main: (main.c) カーネル初期化のエントリポイント ──" },
        { op: "comment", text: "── 4. binit: (bio.c) バッファキャッシュ初期化 (NBUF=15) ──" },
        { op: "comment", text: "── 5. iinit: (alloc.c) スーパーブロック読込、フリーリスト初期化 ──" },
        { op: "comment", text: "── 6. newproc: (slp.c) プロセス0(swapper)を作成 ──" },
        { op: "comment", text: "── 7. fork → プロセス1(init)を作成 ──" },
        { op: "fork", parentPid: 1, childName: "init-exec" },
        { op: "comment", text: "── 8. init: /etc/init を exec ──" },
        { op: "exec", pid: 2, path: "/etc/init", argv: ["init"] },
        { op: "comment", text: "── 9. /etc/rc 実行 (システム初期化スクリプト) ──" },
        { op: "fork", parentPid: 2, childName: "rc" },
        { op: "exec", pid: 3, path: "/bin/sh", argv: ["-c", "/etc/rc"] },
        { op: "exit", pid: 3, code: 0 },
        { op: "wait", pid: 2 },
        { op: "comment", text: "── 10. init が各端末用の getty を fork ──" },
        { op: "fork", parentPid: 2, childName: "getty" },
        { op: "exec", pid: 4, path: "/etc/getty", argv: ["getty", "/dev/tty0"] },
        { op: "comment", text: "── getty: 端末速度設定 → 'login: ' プロンプト表示 ──" },
        { op: "tty_output", pid: 4, device: 1, chars: "login: " },
        { op: "comment", text: "── ユーザーがログイン名を入力 ──" },
        { op: "tty_input", device: 1, chars: "ken\n" },
        { op: "comment", text: "── getty → exec /bin/login ──" },
        { op: "exec", pid: 4, path: "/bin/login", argv: ["login"] },
        { op: "comment", text: "── login: パスワード検証 → exec /bin/sh ──" },
        { op: "exec", pid: 4, path: "/bin/sh", argv: ["/bin/sh"] },
        { op: "comment", text: "── ユーザーのシェルが起動。プロンプト表示 ──" },
        { op: "tty_output", pid: 4, device: 1, chars: "$ " },
        { op: "comment", text: "── プロセス0(swapper/sched)はメモリ管理を担当し続ける ──" },
        { op: "schedule" },
      ],
    }),
  },
  // ─── [34] brk()/データ領域拡張 ───
  {
    name: "brk()/データ領域拡張",
    description: "fork→exec→break(データセグメント拡張)の流れ。V6のsbreak() (sys1.c) によるヒープ拡張",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "comment", text: "── brk()/sbreak(): データ領域の動的拡張 ──" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── break: データセグメントを拡張 (malloc相当) ──" },
        { op: "break", pid: 2, newSize: 4096 },
        { op: "comment", text: "── データセグメントが拡張された。メモリマップを確認 ──" },
      ],
    }),
  },
  // ─── [35] seek()とファイルポインタ ───
  {
    name: "seek()とファイルポインタ",
    description: "seek()のwhence 3モード(先頭/現在位置/末尾)によるファイルポインタ移動",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── ファイルを作成してデータを書き込み ──" },
        { op: "creat", pid: 2, path: "/tmp/seektest.txt", perm: 0o644 },
        { op: "write", pid: 2, fd: 0, data: "ABCDEFGHIJ" },
        { op: "comment", text: "── seek whence=0: ファイル先頭から移動 ──" },
        { op: "seek", pid: 2, fd: 0, offset: 0, whence: 0 },
        { op: "read", pid: 2, fd: 0, size: 5 },
        { op: "comment", text: "── seek whence=2: ファイル末尾から移動 ──" },
        { op: "seek", pid: 2, fd: 0, offset: 0, whence: 2 },
        { op: "close", pid: 2, fd: 0 },
      ],
    }),
  },
  // ─── [36] mknod()とデバイスファイル ───
  {
    name: "mknod()とデバイスファイル",
    description: "mknod()でキャラクタ/ブロックデバイスファイルを作成。V6ではmkdirもmknodで実装",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── mknod: キャラクタデバイス /dev/lp (プリンタ) ──" },
        // V6_IFCHR = 0o020000, 0o020666 = キャラクタデバイス + rw-rw-rw-
        { op: "mknod", pid: 2, path: "/dev/lp", mode: 0o020666, dev: 2 },
        { op: "comment", text: "── mknod: ブロックデバイス /dev/rk1 (ディスク) ──" },
        // V6_IFBLK = 0o060000, 0o060660 = ブロックデバイス + rw-rw----
        { op: "mknod", pid: 2, path: "/dev/rk1", mode: 0o060660, dev: 0 },
        { op: "comment", text: "── stat でデバイスファイルの情報を確認 ──" },
        { op: "stat", pid: 2, path: "/dev/lp" },
        { op: "stat", pid: 2, path: "/dev/rk1" },
      ],
    }),
  },
  // ─── [37] ptrace()デバッグ ───
  {
    name: "ptrace()デバッグ",
    description: "ptrace()による子プロセスのトレース。TRACEME→PEEKDATA→CONTの流れ",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "comment", text: "── ptrace(2): デバッガ(adb)の仕組み ──" },
        { op: "fork", parentPid: 1, childName: "debugger" },
        { op: "exec", pid: 2, path: "/bin/adb", argv: [] },
        { op: "comment", text: "── 子プロセス(被デバッグ対象)をfork ──" },
        { op: "fork", parentPid: 2, childName: "target" },
        { op: "comment", text: "── 子がptrace(TRACEME)で自身をトレース可能にする ──" },
        { op: "ptrace", pid: 3, targetPid: 3, request: 0, addr: 0, data: 0 },
        { op: "comment", text: "── 親がptrace(PEEKDATA)で子のメモリを読む ──" },
        { op: "ptrace", pid: 2, targetPid: 3, request: 2, addr: 0x1000, data: 0 },
        { op: "comment", text: "── 親がptrace(CONT)で子の実行を再開 ──" },
        { op: "ptrace", pid: 2, targetPid: 3, request: 7, addr: 0, data: 0 },
        { op: "comment", text: "── V6のptraceはadbデバッガの基盤。GDBの先祖 ──" },
      ],
    }),
  },
  // ─── [38] grow()スタック自動拡張 ───
  {
    name: "grow()スタック自動拡張",
    description: "スタックオーバーフロー時のMMUトラップとカーネルによるスタック自動拡張",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── grow(): スタックセグメントの自動拡張 ──" },
        { op: "comment", text: "── PDP-11のMMUがスタック範囲外アクセスを検出 → trap ──" },
        { op: "grow", pid: 2, newStackSize: 2048 },
        { op: "comment", text: "── スタックセグメントが拡張された ──" },
      ],
    }),
  },
  // ─── [39] breada()先読みとphysio() RAW I/O ───
  {
    name: "breada()先読みとphysio() RAW I/O",
    description: "breada()による先読みキャッシュとphysio()によるバッファキャッシュバイパスI/O",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── breada(): 通常読み + 先読み(async) ──" },
        { op: "breada", device: 0, blockNum: 100, readAheadBlock: 101 },
        { op: "comment", text: "── physio(): バッファキャッシュをバイパスしたRAW書き込み ──" },
        { op: "physio", pid: 2, device: 0, blockNum: 200, write: true },
        { op: "comment", text: "── physio(): RAW読み込み ──" },
        { op: "physio", pid: 2, device: 0, blockNum: 200, write: false },
        { op: "comment", text: "── breadaはシーケンシャルI/Oの高速化、physioはraw deviceアクセス ──" },
      ],
    }),
  },
  // ─── [40] clock_tick()とcalloutテーブル ───
  {
    name: "clock_tick()とcalloutテーブル",
    description: "クロック割り込み処理: CPU使用量加算、calloutタイマー、優先度再計算",
    build: () => ({
      config: defaultConfig(),
      operations: [
        { op: "boot" },
        { op: "fork", parentPid: 1, childName: "sh" },
        { op: "exec", pid: 2, path: "/bin/sh", argv: [] },
        { op: "comment", text: "── clock_tick: 50Hz(PDP-11 LKS)のクロック割り込み ──" },
        { op: "clock_tick" },
        { op: "clock_tick" },
        { op: "clock_tick" },
        { op: "comment", text: "── scheduleで優先度ベースのプロセス切り替え ──" },
        { op: "schedule" },
        { op: "comment", text: "── clock_tickでcpuUsageが加算され、優先度が再計算される ──" },
      ],
    }),
  },
];

