/* UNIX セマフォ シミュレーター プリセット */

import type { Preset, SimOp, SemInstr } from "./types.js";
import { defaultConfig } from "./engine.js";

export const PRESETS: Preset[] = [
  {
    name: "基本的なセマフォ操作",
    description: "sem_init / sem_wait / sem_post の基本動作",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      sharedVars: [{ name: "counter", value: 0 }],
      mainInstructions: [
        { op: "comment", text: "── カウンティングセマフォの基本操作 ──" },
        { op: "sem_init", name: "sem", value: 1 },
        { op: "sem_wait", name: "sem" },
        { op: "comment", text: "── クリティカルセクション ──" },
        { op: "increment", varName: "counter" },
        { op: "sem_post", name: "sem" },
        { op: "sem_getvalue", name: "sem", into: "val" },
        { op: "comment", text: "── セマフォ値を確認 ──" },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "バイナリセマフォ（Mutex代替）",
    description: "バイナリセマフォによる排他制御",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 2 },
      sharedVars: [{ name: "shared", value: 0 }],
      mainInstructions: [
        { op: "sem_init", name: "bsem", value: 1, type: "binary" },
        { op: "create", name: "worker1", instructions: [
          { op: "sem_wait", name: "bsem" },
          { op: "comment", text: "── worker1: クリティカルセクション ──" },
          { op: "read", varName: "shared", into: "tmp" },
          { op: "write", varName: "shared", value: 10 },
          { op: "sem_post", name: "bsem" },
          { op: "exit" },
        ]},
        { op: "create", name: "worker2", instructions: [
          { op: "sem_wait", name: "bsem" },
          { op: "comment", text: "── worker2: クリティカルセクション ──" },
          { op: "read", varName: "shared", into: "tmp" },
          { op: "write", varName: "shared", value: 20 },
          { op: "sem_post", name: "bsem" },
          { op: "exit" },
        ]},
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "Producer-Consumer",
    description: "セマフォによるプロデューサー・コンシューマーパターン",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 2 },
      sharedVars: [{ name: "buffer", value: 0 }, { name: "produced", value: 0 }, { name: "consumed", value: 0 }],
      mainInstructions: [
        { op: "comment", text: "── バッファサイズ3のProducer-Consumer ──" },
        { op: "sem_init", name: "empty", value: 3 },
        { op: "sem_init", name: "full", value: 0 },
        { op: "sem_init", name: "mutex", value: 1 },
        { op: "create", name: "producer", instructions: [
          // 3個生産
          { op: "sem_wait", name: "empty" },
          { op: "sem_wait", name: "mutex" },
          { op: "increment", varName: "buffer" },
          { op: "increment", varName: "produced" },
          { op: "comment", text: "── 生産: バッファに追加 ──" },
          { op: "sem_post", name: "mutex" },
          { op: "sem_post", name: "full" },

          { op: "sem_wait", name: "empty" },
          { op: "sem_wait", name: "mutex" },
          { op: "increment", varName: "buffer" },
          { op: "increment", varName: "produced" },
          { op: "sem_post", name: "mutex" },
          { op: "sem_post", name: "full" },

          { op: "sem_wait", name: "empty" },
          { op: "sem_wait", name: "mutex" },
          { op: "increment", varName: "buffer" },
          { op: "increment", varName: "produced" },
          { op: "sem_post", name: "mutex" },
          { op: "sem_post", name: "full" },
          { op: "exit" },
        ]},
        { op: "create", name: "consumer", instructions: [
          // 3個消費
          { op: "sem_wait", name: "full" },
          { op: "sem_wait", name: "mutex" },
          { op: "decrement", varName: "buffer" },
          { op: "increment", varName: "consumed" },
          { op: "comment", text: "── 消費: バッファから取得 ──" },
          { op: "sem_post", name: "mutex" },
          { op: "sem_post", name: "empty" },

          { op: "sem_wait", name: "full" },
          { op: "sem_wait", name: "mutex" },
          { op: "decrement", varName: "buffer" },
          { op: "increment", varName: "consumed" },
          { op: "sem_post", name: "mutex" },
          { op: "sem_post", name: "empty" },

          { op: "sem_wait", name: "full" },
          { op: "sem_wait", name: "mutex" },
          { op: "decrement", varName: "buffer" },
          { op: "increment", varName: "consumed" },
          { op: "sem_post", name: "mutex" },
          { op: "sem_post", name: "empty" },
          { op: "exit" },
        ]},
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "comment", text: "── 全アイテム生産・消費完了 ──" },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "Readers-Writers問題",
    description: "セマフォによる読者・書者問題（読者優先）",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 2 },
      sharedVars: [{ name: "data", value: 100 }, { name: "readCount", value: 0 }],
      mainInstructions: [
        { op: "sem_init", name: "rw_mutex", value: 1 },
        { op: "sem_init", name: "rc_mutex", value: 1 },
        { op: "create", name: "reader1", instructions: [
          { op: "sem_wait", name: "rc_mutex" },
          { op: "increment", varName: "readCount" },
          { op: "sem_getvalue", name: "rw_mutex", into: "rw_val" },
          { op: "comment", text: "── readCount==1 なら rw_mutex を取得 ──" },
          { op: "sem_post", name: "rc_mutex" },
          { op: "comment", text: "── reader1: データ読み取り ──" },
          { op: "read", varName: "data", into: "val" },
          { op: "sem_wait", name: "rc_mutex" },
          { op: "decrement", varName: "readCount" },
          { op: "sem_post", name: "rc_mutex" },
          { op: "exit" },
        ]},
        { op: "create", name: "reader2", instructions: [
          { op: "sem_wait", name: "rc_mutex" },
          { op: "increment", varName: "readCount" },
          { op: "sem_post", name: "rc_mutex" },
          { op: "comment", text: "── reader2: データ読み取り ──" },
          { op: "read", varName: "data", into: "val" },
          { op: "sem_wait", name: "rc_mutex" },
          { op: "decrement", varName: "readCount" },
          { op: "sem_post", name: "rc_mutex" },
          { op: "exit" },
        ]},
        { op: "create", name: "writer", instructions: [
          { op: "sleep", ticks: 2 },
          { op: "sem_wait", name: "rw_mutex" },
          { op: "comment", text: "── writer: データ書き込み ──" },
          { op: "write", varName: "data", value: 200 },
          { op: "sem_post", name: "rw_mutex" },
          { op: "exit" },
        ]},
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "join", pid: 3 },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "食事する哲学者",
    description: "5人の哲学者とフォーク（デッドロック回避版）",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 1 },
      sharedVars: [{ name: "meals", value: 0 }],
      mainInstructions: [
        { op: "comment", text: "── 食事する哲学者問題（セマフォで同時着席数を制限） ──" },
        { op: "sem_init", name: "fork0", value: 1 },
        { op: "sem_init", name: "fork1", value: 1 },
        { op: "sem_init", name: "fork2", value: 1 },
        { op: "sem_init", name: "room", value: 2 },
        ...buildPhilosopher(0, "fork0", "fork1"),
        ...buildPhilosopher(1, "fork1", "fork2"),
        ...buildPhilosopher(2, "fork2", "fork0"),
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "join", pid: 3 },
        { op: "comment", text: "── 全哲学者が食事完了 ──" },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "カウンティングセマフォ（リソースプール）",
    description: "N個のリソースを管理するカウンティングセマフォ",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 2 },
      sharedVars: [{ name: "activeUsers", value: 0 }],
      mainInstructions: [
        { op: "comment", text: "── 同時接続数3のリソースプール ──" },
        { op: "sem_init", name: "pool", value: 3 },
        ...buildPoolClient("client1", 1),
        ...buildPoolClient("client2", 2),
        ...buildPoolClient("client3", 3),
        ...buildPoolClient("client4", 4),
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "join", pid: 3 },
        { op: "join", pid: 4 },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "sem_trywait（ノンブロッキング）",
    description: "sem_trywaitによるノンブロッキング取得の試行",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 2 },
      sharedVars: [],
      mainInstructions: [
        { op: "sem_init", name: "resource", value: 1 },
        { op: "create", name: "holder", instructions: [
          { op: "sem_wait", name: "resource" },
          { op: "comment", text: "── holder: リソース保持中 ──" },
          { op: "sleep", ticks: 5 },
          { op: "sem_post", name: "resource" },
          { op: "exit" },
        ]},
        { op: "create", name: "poller", instructions: [
          { op: "sleep", ticks: 1 },
          { op: "sem_trywait", name: "resource" },
          { op: "comment", text: "── poller: 1回目の試行（失敗するはず） ──" },
          { op: "sleep", ticks: 5 },
          { op: "sem_trywait", name: "resource" },
          { op: "comment", text: "── poller: 2回目の試行（成功するはず） ──" },
          { op: "sem_post", name: "resource" },
          { op: "exit" },
        ]},
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "sem_timedwait（タイムアウト）",
    description: "タイムアウト付きセマフォ待機",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      sharedVars: [],
      mainInstructions: [
        { op: "sem_init", name: "slow_resource", value: 0 },
        { op: "create", name: "waiter", instructions: [
          { op: "comment", text: "── タイムアウト3 tickで待機 ──" },
          { op: "sem_timedwait", name: "slow_resource", timeout: 3 },
          { op: "comment", text: "── タイムアウトした（リソース提供されず） ──" },
          { op: "exit" },
        ]},
        { op: "create", name: "fast_waiter", instructions: [
          { op: "sem_init", name: "fast_resource", value: 0 },
          { op: "comment", text: "── タイムアウト10 tickで待機（間に合う） ──" },
          { op: "sem_timedwait", name: "fast_resource", timeout: 10 },
          { op: "exit" },
        ]},
        { op: "create", name: "provider", instructions: [
          { op: "sleep", ticks: 5 },
          { op: "comment", text: "── 5 tick後にfast_resourceを提供 ──" },
          { op: "sem_post", name: "fast_resource" },
          { op: "exit" },
        ]},
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "join", pid: 3 },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "名前付きセマフォ（プロセス間共有）",
    description: "sem_openによるプロセス間セマフォ共有",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 2 },
      sharedVars: [{ name: "ipc_data", value: 0 }],
      mainInstructions: [
        { op: "comment", text: "── 名前付きセマフォでプロセス間同期 ──" },
        { op: "sem_open", name: "/my_sem", value: 1 },
        { op: "create", name: "process_A", instructions: [
          { op: "sem_open", name: "/my_sem", value: 1 },
          { op: "sem_wait", name: "/my_sem" },
          { op: "comment", text: "── process_A: 共有リソースに書き込み ──" },
          { op: "write", varName: "ipc_data", value: 42 },
          { op: "sem_post", name: "/my_sem" },
          { op: "sem_close", name: "/my_sem" },
          { op: "exit" },
        ]},
        { op: "create", name: "process_B", instructions: [
          { op: "sem_open", name: "/my_sem", value: 1 },
          { op: "sem_wait", name: "/my_sem" },
          { op: "comment", text: "── process_B: 共有リソースに書き込み ──" },
          { op: "write", varName: "ipc_data", value: 99 },
          { op: "sem_post", name: "/my_sem" },
          { op: "sem_close", name: "/my_sem" },
          { op: "exit" },
        ]},
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "sem_close", name: "/my_sem" },
        { op: "exit" },
      ],
    }],
  },
  {
    name: "セマフォでのデッドロック",
    description: "セマフォの不適切な使用によるデッドロック",
    build: (): SimOp[] => [{
      type: "execute", config: { ...defaultConfig(), timeSlice: 1 },
      sharedVars: [],
      mainInstructions: [
        { op: "comment", text: "── 2つのセマフォを逆順に取得→デッドロック ──" },
        { op: "sem_init", name: "semA", value: 1 },
        { op: "sem_init", name: "semB", value: 1 },
        { op: "create", name: "proc1", instructions: [
          { op: "sem_wait", name: "semA" },
          { op: "sleep", ticks: 3 },
          { op: "sem_wait", name: "semB" },
          { op: "sem_post", name: "semB" },
          { op: "sem_post", name: "semA" },
          { op: "exit" },
        ]},
        { op: "create", name: "proc2", instructions: [
          { op: "sem_wait", name: "semB" },
          { op: "sleep", ticks: 3 },
          { op: "sem_wait", name: "semA" },
          { op: "sem_post", name: "semA" },
          { op: "sem_post", name: "semB" },
          { op: "exit" },
        ]},
        { op: "join", pid: 1 },
        { op: "join", pid: 2 },
        { op: "exit" },
      ],
    }],
  },
];

/** 哲学者プロセスのビルドヘルパー */
function buildPhilosopher(id: number, left: string, right: string): SemInstr[] {
  return [
    { op: "create", name: `philosopher_${id}`, instructions: [
      { op: "sem_wait", name: "room" },
      { op: "comment", text: `── 哲学者${id}: 部屋に入る ──` },
      { op: "sem_wait", name: left },
      { op: "sem_wait", name: right },
      { op: "comment", text: `── 哲学者${id}: 食事中 ──` },
      { op: "increment", varName: "meals" },
      { op: "sem_post", name: right },
      { op: "sem_post", name: left },
      { op: "sem_post", name: "room" },
      { op: "comment", text: `── 哲学者${id}: 食事完了 ──` },
      { op: "exit" },
    ]},
  ];
}

/** プールクライアントのビルドヘルパー */
function buildPoolClient(name: string, _id: number): SemInstr[] {
  return [
    { op: "create", name, instructions: [
      { op: "sem_wait", name: "pool" },
      { op: "comment", text: `── ${name}: リソース取得 ──` },
      { op: "increment", varName: "activeUsers" },
      { op: "sleep", ticks: 2 },
      { op: "decrement", varName: "activeUsers" },
      { op: "sem_post", name: "pool" },
      { op: "comment", text: `── ${name}: リソース解放 ──` },
      { op: "exit" },
    ]},
  ];
}
