/* UNIX 擬似端末 (PTY) シミュレーター プリセット */

import type { Preset, SimOp } from "./types.js";
import { defaultConfig } from "./engine.js";

export const PRESETS: Preset[] = [
  {
    name: "PTY確保の基本手順",
    description: "posix_openpt → grantpt → unlockpt → ptsname の標準手順",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── PTY確保の4ステップ ──" },
        { op: "posix_openpt" },
        { op: "comment", text: "── /dev/ptmx を open → マスター fd 取得 ──" },
        { op: "grantpt" },
        { op: "comment", text: "── スレーブデバイスのパーミッション設定 ──" },
        { op: "unlockpt" },
        { op: "comment", text: "── スレーブ側のロック解除 ──" },
        { op: "ptsname" },
        { op: "comment", text: "── スレーブデバイスパス取得 ──" },
        { op: "open_slave" },
        { op: "comment", text: "── PTY確保完了: master↔slave ペア成立 ──" },
      ],
    }],
  },
  {
    name: "端末エミュレータ (xterm型)",
    description: "xtermがPTYを使ってシェルを起動する流れ",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── xterm: PTYを確保 ──" },
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "ptsname" },
        { op: "comment", text: "── fork: 子プロセスでシェルを起動 ──" },
        { op: "fork", childName: "bash", childInstrs: [
          { op: "setsid" },
          { op: "open_slave" },
          { op: "ioctl_tiocsctty" },
          { op: "comment", text: "── stdin/stdout/stderrをスレーブに接続 ──" },
          { op: "dup2", srcFd: 5, dstFd: 0 },
          { op: "dup2", srcFd: 5, dstFd: 1 },
          { op: "dup2", srcFd: 5, dstFd: 2 },
          { op: "exec", program: "/bin/bash" },
        ]},
        { op: "comment", text: "── xterm: マスター側でI/Oループ ──" },
        { op: "write_master", data: "ls -la\n" },
        { op: "comment", text: "── キーボード入力 → master write → line disc → slave read ──" },
        { op: "read_master" },
        { op: "comment", text: "── slave write → line disc → master read → 画面描画 ──" },
      ],
    }],
  },
  {
    name: "データフロー (master↔slave)",
    description: "PTYのマスター側とスレーブ側のデータ伝達経路",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "open_slave" },
        { op: "comment", text: "── master→slave: キーボード入力の経路 ──" },
        { op: "write_master", data: "Hello" },
        { op: "comment", text: "── line disciplineを通過: エコー処理、編集 ──" },
        { op: "read_slave" },
        { op: "comment", text: "── slave→master: プログラム出力の経路 ──" },
        { op: "write_slave", data: "World\n" },
        { op: "comment", text: "── line disciplineを通過: NL→CRNL変換等 ──" },
        { op: "read_master" },
        { op: "comment", text: "── 双方向の全二重通信 ──" },
      ],
    }],
  },
  {
    name: "SSH経由のPTY",
    description: "SSHサーバがリモートシェル用にPTYを確保する流れ",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── sshd: クライアント接続を受けてPTYを確保 ──" },
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "ptsname" },
        { op: "comment", text: "── fork: リモートシェル用の子プロセス ──" },
        { op: "fork", childName: "sshd-child", childInstrs: [
          { op: "setsid" },
          { op: "open_slave" },
          { op: "ioctl_tiocsctty" },
          { op: "dup2", srcFd: 5, dstFd: 0 },
          { op: "dup2", srcFd: 5, dstFd: 1 },
          { op: "dup2", srcFd: 5, dstFd: 2 },
          { op: "exec", program: "/bin/bash" },
        ]},
        { op: "comment", text: "── sshd親: ネットワーク↔マスターfdを中継 ──" },
        { op: "write_master", data: "whoami\n" },
        { op: "read_master" },
        { op: "comment", text: "── SSH: ネットワーク → master → line disc → slave → bash ──" },
        { op: "write_master", data: "exit\n" },
      ],
    }],
  },
  {
    name: "tmux/screen (多重化)",
    description: "PTYを多重化してウィンドウを管理する仕組み",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "comment", text: "── tmuxサーバ: 複数のPTYを管理 ──" },
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "open_slave" },
        { op: "comment", text: "── ウィンドウ0: bash ──" },
        { op: "fork", childName: "bash-w0", childInstrs: [
          { op: "setsid" },
          { op: "exec", program: "/bin/bash" },
        ]},
        { op: "write_master", data: "echo window0\n" },
        { op: "comment", text: "── 新しいウィンドウ用にもう1つPTYを確保 ──" },
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "open_slave" },
        { op: "comment", text: "── ウィンドウ1: vim ──" },
        { op: "fork", childName: "vim-w1", childInstrs: [
          { op: "setsid" },
          { op: "exec", program: "/usr/bin/vim" },
        ]},
        { op: "write_master", data: ":q!\n" },
        { op: "comment", text: "── tmux: 複数PTYのマスター側をまとめて管理 ──" },
      ],
    }],
  },
  {
    name: "セッションと制御端末",
    description: "setsid、TIOCSCTTY、セッションリーダーの関係",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "comment", text: "── fork後、子プロセスでsetsid ──" },
        { op: "fork", childName: "session-child", childInstrs: [
          { op: "comment", text: "── setsid: 新セッション作成、制御端末なし ──" },
          { op: "setsid" },
          { op: "comment", text: "── PTYスレーブをopen ──" },
          { op: "open_slave" },
          { op: "comment", text: "── TIOCSCTTY: 制御端末を設定 ──" },
          { op: "ioctl_tiocsctty" },
          { op: "comment", text: "── これでSIGINT/SIGHUPがこの端末から配送される ──" },
        ]},
        { op: "comment", text: "── 親プロセスは元のセッションに留まる ──" },
        { op: "ioctl_tiocgwinsz" },
      ],
    }],
  },
  {
    name: "ウィンドウサイズ変更 (SIGWINCH)",
    description: "TIOCSWINSZ によるウィンドウサイズ通知",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "open_slave" },
        { op: "comment", text: "── 初期ウィンドウサイズ取得 ──" },
        { op: "ioctl_tiocgwinsz" },
        { op: "comment", text: "── ユーザーが端末をリサイズ ──" },
        { op: "ioctl_tiocswinsz", rows: 40, cols: 120 },
        { op: "comment", text: "── SIGWINCH → フォアグラウンドプロセス ──" },
        { op: "send_sigwinch" },
        { op: "ioctl_tiocgwinsz" },
        { op: "comment", text: "── 再度リサイズ ──" },
        { op: "ioctl_tiocswinsz", rows: 25, cols: 80 },
        { op: "send_sigwinch" },
        { op: "ioctl_tiocgwinsz" },
      ],
    }],
  },
  {
    name: "fd の dup2 接続",
    description: "stdin/stdout/stderr をPTYスレーブにdup2する過程",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "ptsname" },
        { op: "fork", childName: "child", childInstrs: [
          { op: "setsid" },
          { op: "open_slave" },
          { op: "ioctl_tiocsctty" },
          { op: "comment", text: "── 元の stdin(0), stdout(1), stderr(2) を閉じる ──" },
          { op: "close_fd", fd: 0 },
          { op: "close_fd", fd: 1 },
          { op: "close_fd", fd: 2 },
          { op: "comment", text: "── PTYスレーブのfdを 0, 1, 2 にdup2 ──" },
          { op: "dup2", srcFd: 5, dstFd: 0 },
          { op: "dup2", srcFd: 5, dstFd: 1 },
          { op: "dup2", srcFd: 5, dstFd: 2 },
          { op: "comment", text: "── これでプログラムのstdioがPTYスレーブに接続 ──" },
          { op: "close_fd", fd: 5 },
          { op: "exec", program: "/bin/sh" },
        ]},
        { op: "comment", text: "── 親: 不要なスレーブfdを閉じる ──" },
        { op: "close_fd", fd: 5 },
        { op: "wait_child" },
      ],
    }],
  },
  {
    name: "SIGHUP（マスター切断）",
    description: "マスター側クローズ時のSIGHUP配送",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "open_slave" },
        { op: "fork", childName: "shell", childInstrs: [
          { op: "setsid" },
          { op: "ioctl_tiocsctty" },
          { op: "exec", program: "/bin/bash" },
        ]},
        { op: "comment", text: "── 正常動作中 ──" },
        { op: "write_master", data: "echo running\n" },
        { op: "read_master" },
        { op: "comment", text: "── マスター側をクローズ（端末切断） ──" },
        { op: "close_fd", fd: 3 },
        { op: "comment", text: "── SIGHUP がセッション全プロセスに配送される ──" },
        { op: "send_sighup" },
        { op: "comment", text: "── nohup/disown で回避可能 ──" },
      ],
    }],
  },
  {
    name: "rawモードとechoオフ",
    description: "パスワード入力やエディタでのPTY設定変更",
    build: (): SimOp[] => [{
      type: "execute", config: defaultConfig(),
      instructions: [
        { op: "posix_openpt" },
        { op: "grantpt" },
        { op: "unlockpt" },
        { op: "open_slave" },
        { op: "comment", text: "── 通常モード: echo=on, canonical=on ──" },
        { op: "write_master", data: "normal input\n" },
        { op: "read_master" },
        { op: "comment", text: "── パスワード入力: echo=off ──" },
        { op: "set_echo", enabled: false },
        { op: "write_master", data: "secret123\n" },
        { op: "comment", text: "── 入力はスレーブに届くがエコーバックなし ──" },
        { op: "read_master" },
        { op: "set_echo", enabled: true },
        { op: "comment", text: "── エディタ: rawモード (canonical=off) ──" },
        { op: "set_canonical", enabled: false },
        { op: "write_master", data: "j" },
        { op: "comment", text: "── rawモード: 1文字ずつ即座に配送 ──" },
        { op: "write_master", data: "k" },
        { op: "set_canonical", enabled: true },
      ],
    }],
  },
];
